/* Goal 24 source-candidate ledger. Not clinical content and not a curriculum. */
(function () {
  "use strict";

  function row(item) {
    return Object.freeze(item);
  }

  window.DOCUTIS_ACQUISITION_LEDGER = Object.freeze({
    schemaVersion: 1,
    checkedOn: "2026-10-01",
    note: "Candidates checked for evidence-grade acquisition. Rejected rows are not cases and must not be rendered as teaching. This ledger is not a diagnosis and not clinician review.",
    candidates: Object.freeze([
      row({
        id: "cand-g24-forehead-mis",
        sourceLabel: "Melanoma in situ, right forehead marked for biopsy",
        sourceUrl: "https://commons.wikimedia.org/wiki/File:Melanoma_in_situ_Right_Forehead.jpg",
        partnerUrl: "https://commons.wikimedia.org/wiki/File:Melanoma_in_situ_Right_Forehead_dermatoscope.jpg",
        author: "Dermanonymous",
        license: "CC BY-SA 4.0",
        modality: "clinical_and_dermoscopy",
        pairedStatus: "source_documented_pair",
        site: "Right forehead",
        verificationStrength: "file_description_not_histopathology",
        status: "accepted",
        reason: "Matching file descriptions, date 2020-02-11, and author. The dermatoscope file calls itself a dermatoscope image of that forehead lesion. Pixels were inspected. Histopathology is not in the description. Integrated as case-g24-01.",
        dateChecked: "2026-10-01",
        integrated: true,
        caseId: "case-g24-01"
      }),
      row({
        id: "cand-g24-back-mm",
        sourceLabel: "Malignant melanoma, left mid back marked for biopsy",
        sourceUrl: "https://commons.wikimedia.org/wiki/File:Malignant_Melanoma_Left_Mid_Back.jpg",
        partnerUrl: "https://commons.wikimedia.org/wiki/File:Malignant_Melanoma_Left_Mid_Back_Dermatoscope.jpg",
        author: "Dermanonymous",
        license: "CC BY-SA 4.0",
        modality: "clinical_and_dermoscopy",
        pairedStatus: "source_documented_pair",
        site: "Left mid back",
        verificationStrength: "file_description_not_histopathology",
        status: "accepted",
        reason: "The dermatoscope file says the same lesion description through a dermatoscope, same date 2020-10-16 and author. Pixels were inspected. No subtype, thickness, stage, or histopathology was in the description. Integrated as case-g24-02.",
        dateChecked: "2026-10-01",
        integrated: true,
        caseId: "case-g24-02"
      }),
      row({
        id: "cand-g24-dermnet-nodular",
        sourceLabel: "Photography of nodular melanoma",
        sourceUrl: "https://commons.wikimedia.org/wiki/File:Photography_of_nodular_melanoma.jpg",
        partnerUrl: null,
        author: "DermNetNZ",
        license: "CC BY 4.0 template on Commons; source is DermNetNZ",
        modality: "clinical",
        pairedStatus: "not_a_pair",
        site: "Not named on the file page checked",
        verificationStrength: "license_blocked",
        status: "rejected_license",
        reason: "The file page credits DermNetNZ via StatPearls. DermNet material is not reused in this project even when a Commons license tag says CC BY 4.0. Not downloaded into the case library.",
        dateChecked: "2026-10-01",
        integrated: false,
        caseId: null
      }),
      row({
        id: "cand-g24-cureus-lmm",
        sourceLabel: "Lentigo maligna melanoma on the left cheek",
        sourceUrl: "https://commons.wikimedia.org/wiki/File:Photograph_of_lentigo_maligna_melanoma.jpg",
        partnerUrl: null,
        author: "Omar Bari, Philip R. Cohen",
        license: "CC BY 3.0",
        modality: "clinical",
        pairedStatus: "not_a_pair",
        site: "Left cheek",
        verificationStrength: "license_blocked",
        status: "rejected_license",
        reason: "The Commons license is CC BY 3.0, which is not an allowed version. Other versions named on the page are histopathology, not dermoscopy. Not downloaded.",
        dateChecked: "2026-10-01",
        integrated: false,
        caseId: null
      }),
      row({
        id: "cand-g24-derm7pt",
        sourceLabel: "Derm7pt clinical and dermoscopic image pairs",
        sourceUrl: "https://github.com/gnapoles/Consistent-Derm7pt",
        partnerUrl: null,
        author: "Derm7pt dataset, as described by the Consistent-Derm7pt repository",
        license: "CC BY-NC-ND 4.0",
        modality: "clinical_and_dermoscopy",
        pairedStatus: "unknown",
        site: "Dataset, not one lesion",
        verificationStrength: "license_blocked",
        status: "rejected_license",
        reason: "The repository states that the dermoscopic images remain under the Derm7pt CC BY-NC-ND 4.0 license. Non-commercial and no-derivatives terms are not allowed. No image was downloaded.",
        dateChecked: "2026-10-01",
        integrated: false,
        caseId: null
      }),
      row({
        id: "cand-g24-brinkmeier-amelanotic-pair",
        sourceLabel: "Amelanotic malignant melanoma, macroscopic and dermoscopic files",
        sourceUrl: "https://commons.wikimedia.org/wiki/File:Amelanotisches,_malignes_Melanom,_%C2%A9wikiderm.de.jpg",
        partnerUrl: "https://commons.wikimedia.org/wiki/File:Dermatoskopie-Bild_eines_amelanotischen,_malignen_Melanoms,_%C2%A9wikiderm.de.jpg",
        author: "Dr. Thomas Brinkmeier",
        license: "CC BY 4.0",
        modality: "clinical_and_dermoscopy",
        pairedStatus: "not_a_pair",
        site: "Not named on either file page",
        verificationStrength: "same_author_and_date_not_same_lesion",
        status: "rejected_not_true_pair",
        reason: "Both files are CC BY 4.0, own work, dated 2017-11-08, and use an amelanotic melanoma label. Neither description says they are the same lesion. Same author, date, and diagnosis are not a pair. The files stay the separate existing cases and were not joined.",
        dateChecked: "2026-10-01",
        integrated: false,
        caseId: null
      }),
      row({
        id: "cand-g24-acral-histo",
        sourceLabel: "Large acral lentiginous melanoma clinical photograph with histopathology files",
        sourceUrl: "https://commons.wikimedia.org/wiki/File:Photography_of_a_large_acral_lentiginous_melanoma.jpg",
        partnerUrl: null,
        author: "Xavier-Júnior and coauthors",
        license: "CC BY 4.0",
        modality: "clinical_and_histopathology",
        pairedStatus: "not_a_pair",
        site: "Acral, already stored",
        verificationStrength: "histopathology_partner_not_dermoscopy",
        status: "rejected_not_true_pair",
        reason: "The Commons gallery for this CC BY 4.0 paper pairs the clinical photograph with histopathology files, not with a dermoscopic frame. Those microscopy files were not added as a clinical-dermoscopy pair. The clinical file is already a case.",
        dateChecked: "2026-10-01",
        integrated: false,
        caseId: null
      }),
      row({
        id: "cand-g24-plos-composite",
        sourceLabel: "Superficial spreading melanoma on dermoscopy, reflectance confocal microscopy and histopathology",
        sourceUrl: "https://commons.wikimedia.org/wiki/File:Superficial_spreading_melanoma_on_dermoscopy,_reflectance_confocal_microscopy_and_histopathology_1.jpg",
        partnerUrl: null,
        author: "Braga and coauthors, PLoS ONE 2013",
        license: "CC BY 4.0",
        modality: "dermoscopy_rcm_histopathology_composite",
        pairedStatus: "not_a_pair",
        site: "Not used",
        verificationStrength: "composite_not_split",
        status: "rejected_not_true_pair",
        reason: "The file is one composite of dermoscopy, reflectance confocal microscopy, and histopathology. It is not a clinical photograph paired with dermoscopy. Panels were not split. Thickness wording in the description was not copied into a case.",
        dateChecked: "2026-10-01",
        integrated: false,
        caseId: null
      }),
      row({
        id: "cand-g24-plos-dermoscopy-only",
        sourceLabel: "Superficial spreading melanoma in situ on dermoscopy",
        sourceUrl: "https://commons.wikimedia.org/wiki/File:Superficial_spreading_melanoma_in_situ_on_dermoscopy.jpg",
        partnerUrl: null,
        author: "Braga and coauthors, PLoS ONE 2013",
        license: "CC BY 4.0",
        modality: "dermoscopy",
        pairedStatus: "not_a_pair",
        site: "Not named as a special site on the file page checked",
        verificationStrength: "no_clinical_partner",
        status: "rejected_teaching_value",
        reason: "Dermoscopy-only file from the same composite paper. No clinical photograph of the same lesion was identified. It is not face, acral, or nail teaching, so it was not ingested. Pixels were not used to author findings.",
        dateChecked: "2026-10-01",
        integrated: false,
        caseId: null
      }),
      row({
        id: "cand-g24-tschandl-nevus",
        sourceLabel: "Small melanocytic nevus, dermatoscope, reticular lines",
        sourceUrl: "https://commons.wikimedia.org/wiki/File:Dermatoscopy_Nevus_Reticular.jpg",
        partnerUrl: null,
        author: "Philipp Tschandl",
        license: "CC BY-SA 4.0",
        modality: "dermoscopy",
        pairedStatus: "not_a_pair",
        site: "Not named",
        verificationStrength: "no_clinical_partner",
        status: "rejected_not_true_pair",
        reason: "CC BY-SA 4.0 dermoscopic file with no clinical photograph of the same lesion identified. It was not paired with a different nevus case. Pixels were not used to author findings.",
        dateChecked: "2026-10-01",
        integrated: false,
        caseId: null
      }),
      row({
        id: "cand-g24-bcn20000",
        sourceLabel: "BCN20000 dermoscopic dataset",
        sourceUrl: "https://pmc.ncbi.nlm.nih.gov/articles/PMC11183228/",
        partnerUrl: null,
        author: "ISIC / Hospital Clínic Barcelona description in the cited data paper",
        license: "CC BY 4.0",
        modality: "dermoscopy",
        pairedStatus: "not_a_pair",
        site: "Dataset, not one lesion",
        verificationStrength: "bulk_dataset_not_a_case",
        status: "rejected_teaching_value",
        reason: "The data paper describes a CC BY 4.0 dermoscopic image collection. A random frame has no documented clinical partner and no single-lesion narrative worth a teaching case. No image was downloaded.",
        dateChecked: "2026-10-01",
        integrated: false,
        caseId: null
      })
    ])
  });
})();
