/* Goal 24 and Goal 25 source-candidate ledger. Not clinical content and not a curriculum. */
(function () {
  "use strict";

  function row(item) {
    return Object.freeze(item);
  }

  window.DOCUTIS_ACQUISITION_LEDGER = Object.freeze({
    schemaVersion: 1,
    checkedOn: "2026-10-01",
    goal25CheckedOn: "2026-10-02",
    note: "Candidates checked for evidence-grade acquisition. Rejected rows are not cases and must not be rendered as teaching. This ledger is not a diagnosis and not clinician review.",
    candidates: Object.freeze([
      row({
        id: "cand-g24-forehead-mis",
        sourceLabel: "Melanoma in situ, right forehead marked for biopsy",
        sourceUrl: "https://commons.wikimedia.org/wiki/File:Melanoma_in_situ_Right_Forehead.jpg",
        partnerUrl: "https://commons.wikimedia.org/wiki/File:Melanoma_in_situ_Right_Forehead_dermatoscope.jpg",
        author: "Dermanonymous",
        license: "CC BY-SA 4.0",
        modality: "clinical_and_dermoscopy",
        pairedStatus: "source_documented_pair",
        site: "Right forehead",
        verificationStrength: "file_description_not_histopathology",
        status: "accepted",
        reason: "Matching file descriptions, date 2020-02-11, and author. The dermatoscope file calls itself a dermatoscope image of that forehead lesion. Pixels were inspected. Histopathology is not in the description. Integrated as case-g24-01.",
        dateChecked: "2026-10-01",
        integrated: true,
        caseId: "case-g24-01"
      }),
      row({
        id: "cand-g24-back-mm",
        sourceLabel: "Malignant melanoma, left mid back marked for biopsy",
        sourceUrl: "https://commons.wikimedia.org/wiki/File:Malignant_Melanoma_Left_Mid_Back.jpg",
        partnerUrl: "https://commons.wikimedia.org/wiki/File:Malignant_Melanoma_Left_Mid_Back_Dermatoscope.jpg",
        author: "Dermanonymous",
        license: "CC BY-SA 4.0",
        modality: "clinical_and_dermoscopy",
        pairedStatus: "source_documented_pair",
        site: "Left mid back",
        verificationStrength: "file_description_not_histopathology",
        status: "accepted",
        reason: "The dermatoscope file says the same lesion description through a dermatoscope, same date 2020-10-16 and author. Pixels were inspected. No subtype, thickness, stage, or histopathology was in the description. Integrated as case-g24-02.",
        dateChecked: "2026-10-01",
        integrated: true,
        caseId: "case-g24-02"
      }),
      row({
        id: "cand-g24-dermnet-nodular",
        sourceLabel: "Photography of nodular melanoma",
        sourceUrl: "https://commons.wikimedia.org/wiki/File:Photography_of_nodular_melanoma.jpg",
        partnerUrl: null,
        author: "DermNetNZ",
        license: "CC BY 4.0 template on Commons; source is DermNetNZ",
        modality: "clinical",
        pairedStatus: "not_a_pair",
        site: "Not named on the file page checked",
        verificationStrength: "license_blocked",
        status: "rejected_license",
        reason: "The file page credits DermNetNZ via StatPearls. DermNet material is not reused in this project even when a Commons license tag says CC BY 4.0. Not downloaded into the case library.",
        dateChecked: "2026-10-01",
        integrated: false,
        caseId: null
      }),
      row({
        id: "cand-g24-cureus-lmm",
        sourceLabel: "Lentigo maligna melanoma on the left cheek",
        sourceUrl: "https://commons.wikimedia.org/wiki/File:Photograph_of_lentigo_maligna_melanoma.jpg",
        partnerUrl: null,
        author: "Omar Bari, Philip R. Cohen",
        license: "CC BY 3.0",
        modality: "clinical",
        pairedStatus: "not_a_pair",
        site: "Left cheek",
        verificationStrength: "license_blocked",
        status: "rejected_license",
        reason: "The Commons license is CC BY 3.0, which is not an allowed version. Other versions named on the page are histopathology, not dermoscopy. Not downloaded.",
        dateChecked: "2026-10-01",
        integrated: false,
        caseId: null
      }),
      row({
        id: "cand-g24-derm7pt",
        sourceLabel: "Derm7pt clinical and dermoscopic image pairs",
        sourceUrl: "https://github.com/gnapoles/Consistent-Derm7pt",
        partnerUrl: null,
        author: "Derm7pt dataset, as described by the Consistent-Derm7pt repository",
        license: "CC BY-NC-ND 4.0",
        modality: "clinical_and_dermoscopy",
        pairedStatus: "unknown",
        site: "Dataset, not one lesion",
        verificationStrength: "license_blocked",
        status: "rejected_license",
        reason: "The repository states that the dermoscopic images remain under the Derm7pt CC BY-NC-ND 4.0 license. Non-commercial and no-derivatives terms are not allowed. No image was downloaded.",
        dateChecked: "2026-10-01",
        integrated: false,
        caseId: null
      }),
      row({
        id: "cand-g24-brinkmeier-amelanotic-pair",
        sourceLabel: "Amelanotic malignant melanoma, macroscopic and dermoscopic files",
        sourceUrl: "https://commons.wikimedia.org/wiki/File:Amelanotisches,_malignes_Melanom,_%C2%A9wikiderm.de.jpg",
        partnerUrl: "https://commons.wikimedia.org/wiki/File:Dermatoskopie-Bild_eines_amelanotischen,_malignen_Melanoms,_%C2%A9wikiderm.de.jpg",
        author: "Dr. Thomas Brinkmeier",
        license: "CC BY 4.0",
        modality: "clinical_and_dermoscopy",
        pairedStatus: "not_a_pair",
        site: "Not named on either file page",
        verificationStrength: "same_author_and_date_not_same_lesion",
        status: "rejected_not_true_pair",
        reason: "Both files are CC BY 4.0, own work, dated 2017-11-08, and use an amelanotic melanoma label. Neither description says they are the same lesion. Same author, date, and diagnosis are not a pair. The files stay the separate existing cases and were not joined.",
        dateChecked: "2026-10-01",
        integrated: false,
        caseId: null
      }),
      row({
        id: "cand-g24-acral-histo",
        sourceLabel: "Large acral lentiginous melanoma clinical photograph with histopathology files",
        sourceUrl: "https://commons.wikimedia.org/wiki/File:Photography_of_a_large_acral_lentiginous_melanoma.jpg",
        partnerUrl: null,
        author: "Xavier-Júnior and coauthors",
        license: "CC BY 4.0",
        modality: "clinical_and_histopathology",
        pairedStatus: "not_a_pair",
        site: "Acral, already stored",
        verificationStrength: "histopathology_partner_not_dermoscopy",
        status: "rejected_not_true_pair",
        reason: "The Commons gallery for this CC BY 4.0 paper pairs the clinical photograph with histopathology files, not with a dermoscopic frame. Those microscopy files were not added as a clinical-dermoscopy pair. The clinical file is already a case.",
        dateChecked: "2026-10-01",
        integrated: false,
        caseId: null
      }),
      row({
        id: "cand-g24-plos-composite",
        sourceLabel: "Superficial spreading melanoma on dermoscopy, reflectance confocal microscopy and histopathology",
        sourceUrl: "https://commons.wikimedia.org/wiki/File:Superficial_spreading_melanoma_on_dermoscopy,_reflectance_confocal_microscopy_and_histopathology_1.jpg",
        partnerUrl: null,
        author: "Braga and coauthors, PLoS ONE 2013",
        license: "CC BY 4.0",
        modality: "dermoscopy_rcm_histopathology_composite",
        pairedStatus: "not_a_pair",
        site: "Not used",
        verificationStrength: "composite_not_split",
        status: "rejected_not_true_pair",
        reason: "The file is one composite of dermoscopy, reflectance confocal microscopy, and histopathology. It is not a clinical photograph paired with dermoscopy. Panels were not split. Thickness wording in the description was not copied into a case.",
        dateChecked: "2026-10-01",
        integrated: false,
        caseId: null
      }),
      row({
        id: "cand-g24-plos-dermoscopy-only",
        sourceLabel: "Superficial spreading melanoma in situ on dermoscopy",
        sourceUrl: "https://commons.wikimedia.org/wiki/File:Superficial_spreading_melanoma_in_situ_on_dermoscopy.jpg",
        partnerUrl: null,
        author: "Braga and coauthors, PLoS ONE 2013",
        license: "CC BY 4.0",
        modality: "dermoscopy",
        pairedStatus: "not_a_pair",
        site: "Not named as a special site on the file page checked",
        verificationStrength: "no_clinical_partner",
        status: "rejected_teaching_value",
        reason: "Dermoscopy-only file from the same composite paper. No clinical photograph of the same lesion was identified. It is not face, acral, or nail teaching, so it was not ingested. Pixels were not used to author findings.",
        dateChecked: "2026-10-01",
        integrated: false,
        caseId: null
      }),
      row({
        id: "cand-g24-tschandl-nevus",
        sourceLabel: "Small melanocytic nevus, dermatoscope, reticular lines",
        sourceUrl: "https://commons.wikimedia.org/wiki/File:Dermatoscopy_Nevus_Reticular.jpg",
        partnerUrl: null,
        author: "Philipp Tschandl",
        license: "CC BY-SA 4.0",
        modality: "dermoscopy",
        pairedStatus: "not_a_pair",
        site: "Not named",
        verificationStrength: "no_clinical_partner",
        status: "rejected_not_true_pair",
        reason: "CC BY-SA 4.0 dermoscopic file with no clinical photograph of the same lesion identified. It was not paired with a different nevus case. Pixels were not used to author findings.",
        dateChecked: "2026-10-01",
        integrated: false,
        caseId: null
      }),
      row({
        id: "cand-g24-bcn20000",
        sourceLabel: "BCN20000 dermoscopic dataset",
        sourceUrl: "https://pmc.ncbi.nlm.nih.gov/articles/PMC11183228/",
        partnerUrl: null,
        author: "ISIC / Hospital Clínic Barcelona description in the cited data paper",
        license: "CC BY 4.0",
        modality: "dermoscopy",
        pairedStatus: "not_a_pair",
        site: "Dataset, not one lesion",
        verificationStrength: "bulk_dataset_not_a_case",
        status: "rejected_teaching_value",
        reason: "The data paper describes a CC BY 4.0 dermoscopic image collection. A random frame has no documented clinical partner and no single-lesion narrative worth a teaching case. No image was downloaded.",
        dateChecked: "2026-10-01",
        integrated: false,
        caseId: null
      }),
      row({
        "goal": 25,
        "partnerUrl": null,
        "integrated": true,
        "caseId": "case-g25-01",
        "dateChecked": "2026-10-02",
        "thirdPartyExclusion": false,
        "localizationReadiness": "localization_ready",
        "extraction": [
          {
            "asset": "assets/media/cases/case-33-clinical.jpg",
            "imageType": "clinical",
            "figure": "Figure 2",
            "panel": "A",
            "sourceFile": "PMC figure file cancers-18-02183-g002.jpg (PMC13406897.1)",
            "sourceSha256": "7c4b404f062fccda702d716a8312c3335af1c88158c7def83ff9d0128608f942",
            "box": [
              0,
              0,
              361,
              268
            ],
            "method": "Pillow crop of the pixel box (left, top, right, bottom), saved as JPEG quality 90 without metadata",
            "assetSha256": "20bca7e242ef77be6e22a617900f047e7efae449bf75105895b14c4567e1e38c"
          },
          {
            "asset": "assets/media/cases/case-33-dermoscopy.jpg",
            "imageType": "dermoscopy",
            "figure": "Figure 2",
            "panel": "B",
            "sourceFile": "PMC figure file cancers-18-02183-g002.jpg (PMC13406897.1)",
            "sourceSha256": "7c4b404f062fccda702d716a8312c3335af1c88158c7def83ff9d0128608f942",
            "box": [
              363,
              0,
              723,
              268
            ],
            "method": "Pillow crop of the pixel box (left, top, right, bottom), saved as JPEG quality 90 without metadata",
            "assetSha256": "1e2091ed0c5d825d8b3dfa675ec932fd77ed9d8c491d7b54e4aa3040ad3704a3"
          }
        ],
        "id": "cand-g25-cancers-mis-thigh",
        "diagnosisLabel": "Melanoma in situ",
        "sourceLabel": "Cancers 2026 Figure 2, Case 1: 5 mm pigmented lesion on the right thigh",
        "sourceUrl": "https://doi.org/10.3390/cancers18142183",
        "author": "Vincenzo De Giorgi and coauthors, University of Florence",
        "license": "CC BY 4.0",
        "modality": "clinical_and_dermoscopy",
        "pairedStatus": "same_lesion_confirmed",
        "site": "Right thigh",
        "verificationStrength": "histopathology_in_figure_caption",
        "verificationMethod": "histopathology",
        "histopathology": "present_figure_caption",
        "dermoscopicTeachingValue": "Atypical pigment network clearly visible; a few small dark dots probable.",
        "specialSiteValue": "none",
        "status": "accepted",
        "reason": "Gold gate and pattern-rich gate. Panels A and B are labeled Case 1 with one histopathology sentence. Article license text and link are CC BY 4.0 with no third-party credit. Written consent to publication is stated. Pixels were inspected."
      }),
      row({
        "goal": 25,
        "partnerUrl": null,
        "integrated": true,
        "caseId": "case-g25-02",
        "dateChecked": "2026-10-02",
        "thirdPartyExclusion": false,
        "localizationReadiness": "localization_uncertain",
        "extraction": [
          {
            "asset": "assets/media/cases/case-34-clinical.jpg",
            "imageType": "clinical",
            "figure": "Figure 2",
            "panel": "C",
            "sourceFile": "PMC figure file cancers-18-02183-g002.jpg (PMC13406897.1)",
            "sourceSha256": "7c4b404f062fccda702d716a8312c3335af1c88158c7def83ff9d0128608f942",
            "box": [
              0,
              270,
              361,
              538
            ],
            "method": "Pillow crop of the pixel box (left, top, right, bottom), saved as JPEG quality 90 without metadata",
            "assetSha256": "3cb08364c5e0eb24b16ec701ed82676974ee93e0bb661339ef05bfa09610d34a"
          },
          {
            "asset": "assets/media/cases/case-34-dermoscopy.jpg",
            "imageType": "dermoscopy",
            "figure": "Figure 2",
            "panel": "D",
            "sourceFile": "PMC figure file cancers-18-02183-g002.jpg (PMC13406897.1)",
            "sourceSha256": "7c4b404f062fccda702d716a8312c3335af1c88158c7def83ff9d0128608f942",
            "box": [
              363,
              270,
              723,
              538
            ],
            "method": "Pillow crop of the pixel box (left, top, right, bottom), saved as JPEG quality 90 without metadata",
            "assetSha256": "781637b095f84a09fef8566498537db9493d43d0193c888ee6654af3cc8f0af0"
          }
        ],
        "id": "cand-g25-cancers-nevus-leg",
        "diagnosisLabel": "Lentiginous melanocytic nevus with cytologic atypia",
        "sourceLabel": "Cancers 2026 Figure 2, Case 2: 5 mm pigmented lesion on the right lower leg",
        "sourceUrl": "https://doi.org/10.3390/cancers18142183",
        "author": "Vincenzo De Giorgi and coauthors, University of Florence",
        "license": "CC BY 4.0",
        "modality": "clinical_and_dermoscopy",
        "pairedStatus": "same_lesion_confirmed",
        "site": "Right lower leg",
        "verificationStrength": "histopathology_in_figure_caption",
        "verificationMethod": "histopathology",
        "histopathology": "present_figure_caption",
        "dermoscopicTeachingValue": "Atypical pigment network clearly visible; shares the feature with the melanoma in situ in the same figure.",
        "specialSiteValue": "none",
        "status": "accepted",
        "reason": "Contrastive gate and pattern-rich gate. A histopathology-confirmed benign mimic paired with the melanoma in situ from the same figure. Bubbles and hairs cover parts of the net, so localization stays uncertain."
      }),
      row({
        "goal": 25,
        "partnerUrl": null,
        "integrated": true,
        "caseId": "case-g25-03",
        "dateChecked": "2026-10-02",
        "thirdPartyExclusion": false,
        "localizationReadiness": "localization_uncertain",
        "extraction": [
          {
            "asset": "assets/media/cases/case-35-clinical.jpg",
            "imageType": "clinical",
            "figure": "Figure 5",
            "panel": "A",
            "sourceFile": "article PDF page 8, image object 173 (PMC9445057.1)",
            "sourceSha256": "1ebeefcf60dd7388981435d264d7d913a2b09f4c3b69f8274b88a06273c42c7f",
            "box": [
              0,
              0,
              832,
              1003
            ],
            "method": "Pillow crop of the pixel box (left, top, right, bottom), saved as JPEG quality 90 without metadata",
            "assetSha256": "7c9e4b1d0ea2267c1081236b03baae270bb59208844324eb401cd961e1d0c9f0"
          },
          {
            "asset": "assets/media/cases/case-35-dermoscopy.jpg",
            "imageType": "dermoscopy",
            "figure": "Figure 5",
            "panel": "B",
            "sourceFile": "article PDF page 8, image object 173 (PMC9445057.1)",
            "sourceSha256": "1ebeefcf60dd7388981435d264d7d913a2b09f4c3b69f8274b88a06273c42c7f",
            "box": [
              835,
              0,
              1535,
              1003
            ],
            "method": "Pillow crop of the pixel box (left, top, right, bottom), saved as JPEG quality 90 without metadata",
            "assetSha256": "2ca1bc48d2f279b7c51a26dcd5fb31a40ce3f15baa14c82af8e4a053da6e2146"
          }
        ],
        "id": "cand-g25-scalp-amelanotic-nm",
        "diagnosisLabel": "Nodular melanoma, amelanotic",
        "sourceLabel": "Scientific Reports 2022 Figure 5: amelanotic papule in the scalp vertex",
        "sourceUrl": "https://doi.org/10.1038/s41598-022-17108-z",
        "author": "Ana Carolina Porto and coauthors, A.C. Camargo Cancer Center",
        "license": "CC BY 4.0",
        "modality": "clinical_and_dermoscopy",
        "pairedStatus": "same_lesion_confirmed",
        "site": "Scalp vertex",
        "verificationStrength": "histopathology_in_figure_caption",
        "verificationMethod": "histopathology",
        "histopathology": "present_figure_caption",
        "dermoscopicTeachingValue": "Dotted and short linear vessels probable; second positive example of mixed vessels.",
        "specialSiteValue": "none",
        "status": "accepted",
        "reason": "Gold gate and repetition of an existing structure. Caption names panel B the dermoscopic image of the lesion and gives the histopathology. The PDF-embedded figure was used for resolution. Vessels are fine, so localization stays uncertain."
      }),
      row({
        "goal": 25,
        "partnerUrl": null,
        "integrated": true,
        "caseId": "case-g25-04",
        "dateChecked": "2026-10-02",
        "thirdPartyExclusion": false,
        "localizationReadiness": "localization_ready",
        "extraction": [
          {
            "asset": "assets/media/cases/case-36-clinical.jpg",
            "imageType": "clinical",
            "figure": "Figure 2",
            "panel": "a",
            "sourceFile": "article PDF page 4, image object 8 (PMC13342755.1)",
            "sourceSha256": "d1f0bb44313b192ef232ff3ed21920d3d04c6b51265e97541d7927ad4a3a1207",
            "box": [
              0,
              0,
              590,
              1125
            ],
            "method": "Pillow crop of the pixel box (left, top, right, bottom), saved as JPEG quality 90 without metadata",
            "assetSha256": "f4104b35a6c946f1d3bcd99b4aab84fcdcabb9ce12ce7b75bc135d4ebff2b184"
          },
          {
            "asset": "assets/media/cases/case-36-dermoscopy.jpg",
            "imageType": "dermoscopy",
            "figure": "Figure 2",
            "panel": "b",
            "sourceFile": "article PDF page 4, image object 8 (PMC13342755.1)",
            "sourceSha256": "d1f0bb44313b192ef232ff3ed21920d3d04c6b51265e97541d7927ad4a3a1207",
            "box": [
              593,
              0,
              1325,
              555
            ],
            "method": "Pillow crop of the pixel box (left, top, right, bottom), saved as JPEG quality 90 without metadata",
            "assetSha256": "9daffc8492ea5c70b6a70c79ebac122ff5b35f07d35ef6af5a9fcf760406d7b4"
          }
        ],
        "id": "cand-g25-heel-mis",
        "diagnosisLabel": "Acral melanoma in situ",
        "sourceLabel": "International Journal of Dermatology 2026 Figure 2: melanoma in situ on the left heel",
        "sourceUrl": "https://doi.org/10.1111/ijd.70384",
        "author": "Handan Merve Erol Mart and coauthors, Ankara University",
        "license": "CC BY 4.0",
        "modality": "clinical_and_dermoscopy",
        "pairedStatus": "same_lesion_confirmed",
        "site": "Left heel, plantar sole",
        "verificationStrength": "histopathology_in_article_methods",
        "verificationMethod": "histopathology",
        "histopathology": "present_article_methods",
        "dermoscopicTeachingValue": "Broad parallel pigmented bands; ridge assignment probable from band width.",
        "specialSiteValue": "acral",
        "status": "accepted",
        "reason": "Special-site gate and gold gate at study level. The methods say melanomas were pathology confirmed. Panels c to e were not used. Pixels were inspected at PDF resolution."
      }),
      row({
        "goal": 25,
        "partnerUrl": null,
        "integrated": true,
        "caseId": "case-g25-05",
        "dateChecked": "2026-10-02",
        "thirdPartyExclusion": false,
        "localizationReadiness": "localization_uncertain",
        "extraction": [
          {
            "asset": "assets/media/cases/case-37-clinical.jpg",
            "imageType": "clinical",
            "figure": "Figure 1",
            "panel": "e",
            "sourceFile": "PMC figure file diagnostics-14-02571-g001b.jpg (PMC11593280.1)",
            "sourceSha256": "4d45ed4504f7467436a184fc4a6730c17a3a756d2ced5bb4ff9a309a137c05fb",
            "box": [
              5,
              337,
              385,
              624
            ],
            "method": "Pillow crop of the pixel box (left, top, right, bottom), saved as JPEG quality 90 without metadata",
            "assetSha256": "87b65469afd3018110af5c11bfa0e68567566deab12ac4ffd5890b880ea4489b"
          },
          {
            "asset": "assets/media/cases/case-37-dermoscopy.jpg",
            "imageType": "dermoscopy",
            "figure": "Figure 1",
            "panel": "f",
            "sourceFile": "PMC figure file diagnostics-14-02571-g001b.jpg (PMC11593280.1)",
            "sourceSha256": "4d45ed4504f7467436a184fc4a6730c17a3a756d2ced5bb4ff9a309a137c05fb",
            "box": [
              392,
              337,
              774,
              624
            ],
            "method": "Pillow crop of the pixel box (left, top, right, bottom), saved as JPEG quality 90 without metadata",
            "assetSha256": "fef0a8958681e289991c09c06590f58c493974aa1264101aa7b54441f5ded070"
          }
        ],
        "id": "cand-g25-periorbital-lm",
        "diagnosisLabel": "Lentigo maligna",
        "sourceLabel": "Diagnostics 2024 Figure 1 panels e and f: lentigo maligna, periorbital",
        "sourceUrl": "https://doi.org/10.3390/diagnostics14222571",
        "author": "Giovanni Rubegni and coauthors, University of Siena",
        "license": "CC BY 4.0",
        "modality": "clinical_and_dermoscopy",
        "pairedStatus": "source_documented_pair",
        "site": "Face, periorbital region",
        "verificationStrength": "histopathology_in_article_methods",
        "verificationMethod": "histopathology",
        "histopathology": "present_article_methods",
        "dermoscopicTeachingValue": "Gray dots around follicles probable; facial pseudo-network clear.",
        "specialSiteValue": "face",
        "status": "accepted",
        "reason": "Special-site gate and contrastive gate. The caption pairs panels by corresponding letters; the methods say histological diagnoses were blinded for the study lesions. Rhomboidal structures were not claimed."
      }),
      row({
        "goal": 25,
        "partnerUrl": null,
        "integrated": true,
        "caseId": "case-g25-06",
        "dateChecked": "2026-10-02",
        "thirdPartyExclusion": false,
        "localizationReadiness": "localization_ready",
        "extraction": [
          {
            "asset": "assets/media/cases/case-38-clinical.jpg",
            "imageType": "clinical",
            "figure": "Figure 1",
            "panel": "c",
            "sourceFile": "PMC figure file diagnostics-14-02571-g001b.jpg (PMC11593280.1)",
            "sourceSha256": "4d45ed4504f7467436a184fc4a6730c17a3a756d2ced5bb4ff9a309a137c05fb",
            "box": [
              5,
              3,
              385,
              290
            ],
            "method": "Pillow crop of the pixel box (left, top, right, bottom), saved as JPEG quality 90 without metadata",
            "assetSha256": "236d7086e2495282b237cf06cc1c5a0def14f5b04a8b7f0487c6eb909f9cfc66"
          },
          {
            "asset": "assets/media/cases/case-38-dermoscopy.jpg",
            "imageType": "dermoscopy",
            "figure": "Figure 1",
            "panel": "d",
            "sourceFile": "PMC figure file diagnostics-14-02571-g001b.jpg (PMC11593280.1)",
            "sourceSha256": "4d45ed4504f7467436a184fc4a6730c17a3a756d2ced5bb4ff9a309a137c05fb",
            "box": [
              392,
              3,
              774,
              290
            ],
            "method": "Pillow crop of the pixel box (left, top, right, bottom), saved as JPEG quality 90 without metadata",
            "assetSha256": "bddac1356b8dbf0db117bbbad53323366b139536d44d2f290c2ecf822a4012f6"
          }
        ],
        "id": "cand-g25-periorbital-sl",
        "diagnosisLabel": "Solar lentigo",
        "sourceLabel": "Diagnostics 2024 Figure 1 panels c and d: solar lentigo, periorbital",
        "sourceUrl": "https://doi.org/10.3390/diagnostics14222571",
        "author": "Giovanni Rubegni and coauthors, University of Siena",
        "license": "CC BY 4.0",
        "modality": "clinical_and_dermoscopy",
        "pairedStatus": "source_documented_pair",
        "site": "Face, periorbital region, upper eyelid",
        "verificationStrength": "histopathology_in_article_methods",
        "verificationMethod": "histopathology",
        "histopathology": "present_article_methods",
        "dermoscopicTeachingValue": "Facial pseudo-network clear; gray dots around follicles not seen.",
        "specialSiteValue": "face",
        "status": "accepted",
        "reason": "Special-site gate and contrastive gate. Benign facial mimic of lentigo maligna from the same figure, with a feature that differs in these frames."
      }),
      row({
        "goal": 25,
        "partnerUrl": null,
        "integrated": false,
        "caseId": null,
        "dateChecked": "2026-10-02",
        "thirdPartyExclusion": false,
        "localizationReadiness": null,
        "extraction": [],
        "id": "cand-g25-periorbital-lmm",
        "diagnosisLabel": "Lentigo maligna melanoma",
        "sourceLabel": "Diagnostics 2024 Figure 1 panels i and j: lentigo maligna melanoma, periorbital",
        "sourceUrl": "https://doi.org/10.3390/diagnostics14222571",
        "author": "Giovanni Rubegni and coauthors, University of Siena",
        "license": "CC BY 4.0",
        "modality": "clinical_and_dermoscopy",
        "pairedStatus": "source_documented_pair",
        "site": "Face, nose and medial canthus",
        "verificationStrength": "histopathology_in_article_methods",
        "verificationMethod": "histopathology",
        "histopathology": "present_article_methods",
        "dermoscopicTeachingValue": "Blue-gray areas and follicular involvement visible at figure size; not encoded.",
        "specialSiteValue": "face",
        "status": "candidate",
        "reason": "Passes the special-site and gold gates at study level. Deferred to keep Goal 25 small. The clinical panel carries source masks over the eyes and marker ink. A future third facial example of gray around follicles."
      }),
      row({
        "goal": 25,
        "partnerUrl": null,
        "integrated": false,
        "caseId": null,
        "dateChecked": "2026-10-02",
        "thirdPartyExclusion": false,
        "localizationReadiness": null,
        "extraction": [],
        "id": "cand-g25-periorbital-pak",
        "diagnosisLabel": "Pigmented actinic keratosis",
        "sourceLabel": "Diagnostics 2024 Figure 1 panels a and b: pigmented actinic keratosis, periorbital",
        "sourceUrl": "https://doi.org/10.3390/diagnostics14222571",
        "author": "Giovanni Rubegni and coauthors, University of Siena",
        "license": "CC BY 4.0",
        "modality": "clinical_and_dermoscopy",
        "pairedStatus": "source_documented_pair",
        "site": "Face, cheek below the eye",
        "verificationStrength": "histopathology_in_article_methods",
        "verificationMethod": "histopathology",
        "histopathology": "present_article_methods",
        "dermoscopicTeachingValue": "Reticular brown pattern sparing follicles at modest resolution.",
        "specialSiteValue": "face",
        "status": "candidate",
        "reason": "A non-melanocytic facial mimic of lentigo maligna. Deferred; the dermoscopic panel is smaller than the other periorbital panels."
      }),
      row({
        "goal": 25,
        "partnerUrl": null,
        "integrated": false,
        "caseId": null,
        "dateChecked": "2026-10-02",
        "thirdPartyExclusion": false,
        "localizationReadiness": null,
        "extraction": [],
        "id": "cand-g25-periorbital-sk-sl",
        "diagnosisLabel": "Seborrheic keratosis combined with solar lentigo",
        "sourceLabel": "Diagnostics 2024 Figure 1 panels g and h",
        "sourceUrl": "https://doi.org/10.3390/diagnostics14222571",
        "author": "Giovanni Rubegni and coauthors, University of Siena",
        "license": "CC BY 4.0",
        "modality": "clinical_and_dermoscopy",
        "pairedStatus": "source_documented_pair",
        "site": "Face, upper eyelid",
        "verificationStrength": "histopathology_in_article_methods",
        "verificationMethod": "histopathology",
        "histopathology": "present_article_methods",
        "dermoscopicTeachingValue": "Mixed lesion with circular dotted overlays in the dermoscopic panel.",
        "specialSiteValue": "face",
        "status": "rejected_teaching_value",
        "reason": "A combined lesion is a poor first facial benign example, and two round dotted overlays in the dermoscopic panel are not explained by the caption."
      }),
      row({
        "goal": 25,
        "partnerUrl": null,
        "integrated": false,
        "caseId": null,
        "dateChecked": "2026-10-02",
        "thirdPartyExclusion": false,
        "localizationReadiness": null,
        "extraction": [],
        "id": "cand-g25-acral-reed-nevus",
        "diagnosisLabel": "Acral Reed nevus",
        "sourceLabel": "Anais Brasileiros de Dermatologia 2023: acral Reed nevus with parallel ridge pattern",
        "sourceUrl": "https://doi.org/10.1016/j.abd.2021.05.022",
        "author": "Elena Canal-Garcia and coauthors",
        "license": "CC BY 4.0",
        "modality": "clinical_dermoscopy_histopathology_composite",
        "pairedStatus": "same_lesion_confirmed",
        "site": "Volar finger",
        "verificationStrength": "histopathology_panels_in_same_figure",
        "verificationMethod": "histopathology",
        "histopathology": "present_figure_caption",
        "dermoscopicTeachingValue": "Very dark pigment; ridge assignment uncertain in pixels.",
        "specialSiteValue": "acral",
        "status": "rejected_low_dermoscopic_signal",
        "reason": "Histopathology-confirmed benign acral lesion, but the pigment is so dark that the ridge-or-furrow assignment is uncertain in the pixels. As the only benign acral case it would teach an exception before the rule."
      }),
      row({
        "goal": 25,
        "partnerUrl": null,
        "integrated": false,
        "caseId": null,
        "dateChecked": "2026-10-02",
        "thirdPartyExclusion": false,
        "localizationReadiness": null,
        "extraction": [],
        "id": "cand-g25-ijd-palm-invasive",
        "diagnosisLabel": "Invasive acral melanoma",
        "sourceLabel": "International Journal of Dermatology 2026 Figure 3: invasive melanoma on the right palm",
        "sourceUrl": "https://doi.org/10.1111/ijd.70384",
        "author": "Handan Merve Erol Mart and coauthors, Ankara University",
        "license": "CC BY 4.0",
        "modality": "clinical_and_dermoscopy",
        "pairedStatus": "same_lesion_confirmed",
        "site": "Right palm",
        "verificationStrength": "histopathology_in_article_methods",
        "verificationMethod": "histopathology",
        "histopathology": "present_article_methods",
        "dermoscopicTeachingValue": "Caption reports parallel ridge pattern with blue-white areas; pixels not inspected.",
        "specialSiteValue": "acral",
        "status": "candidate",
        "reason": "Same article as the accepted heel case. A future second acral example. Pixels were not inspected, so no structure is claimed."
      }),
      row({
        "goal": 25,
        "partnerUrl": null,
        "integrated": false,
        "caseId": null,
        "dateChecked": "2026-10-02",
        "thirdPartyExclusion": false,
        "localizationReadiness": null,
        "extraction": [],
        "id": "cand-g25-scirep-desmoplastic",
        "diagnosisLabel": "Desmoplastic melanoma",
        "sourceLabel": "Scientific Reports 2022 Figure 6: amelanotic plaque in the scalp",
        "sourceUrl": "https://doi.org/10.1038/s41598-022-17108-z",
        "author": "Ana Carolina Porto and coauthors, A.C. Camargo Cancer Center",
        "license": "CC BY 4.0",
        "modality": "clinical_and_dermoscopy",
        "pairedStatus": "same_lesion_confirmed",
        "site": "Scalp",
        "verificationStrength": "histopathology_in_figure_caption",
        "verificationMethod": "histopathology",
        "histopathology": "present_figure_caption",
        "dermoscopicTeachingValue": "Caption reports polymorphous vessels; pixels not inspected.",
        "specialSiteValue": "none",
        "status": "candidate",
        "reason": "A possible third mixed-vessel example from the same article. Deferred; pixels were not inspected and the figure is a short strip."
      }),
      row({
        "goal": 25,
        "partnerUrl": null,
        "integrated": false,
        "caseId": null,
        "dateChecked": "2026-10-02",
        "thirdPartyExclusion": false,
        "localizationReadiness": null,
        "extraction": [],
        "id": "cand-g25-dermatofibroma-lcoct",
        "diagnosisLabel": "Dermatofibroma",
        "sourceLabel": "Cancers 2026 LC-OCT study Figure 2: dermatofibroma on the left shoulder",
        "sourceUrl": "https://pmc.ncbi.nlm.nih.gov/articles/PMC12784862/",
        "author": "Authors of the Cancers 2026 LC-OCT basal cell carcinoma study",
        "license": "CC BY 4.0",
        "modality": "clinical_dermoscopy_histopathology_composite",
        "pairedStatus": "same_lesion_confirmed",
        "site": "Left shoulder",
        "verificationStrength": "histopathology_panels_in_same_figure",
        "verificationMethod": "histopathology",
        "histopathology": "present_figure_caption",
        "dermoscopicTeachingValue": "Caption reports central scar-like area and peripheral pigment; pixels not inspected.",
        "specialSiteValue": "none",
        "status": "candidate",
        "reason": "Docutis has no dermatofibroma case. A future benign mimic. Pixels were not inspected."
      }),
      row({
        "goal": 25,
        "partnerUrl": null,
        "integrated": false,
        "caseId": null,
        "dateChecked": "2026-10-02",
        "thirdPartyExclusion": false,
        "localizationReadiness": null,
        "extraction": [],
        "id": "cand-g25-dpc-face-mis",
        "diagnosisLabel": "Melanoma in situ of the cheek",
        "sourceLabel": "Dermatology Practical and Conceptual 2021: melanocytic lesions on the face, Figure 2",
        "sourceUrl": "https://pmc.ncbi.nlm.nih.gov/articles/PMC8480450/",
        "author": "Deinlein and coauthors",
        "license": "Conflicting: link to CC BY 4.0, text says BY-NC-4.0 noncommercial",
        "modality": "clinical_and_dermoscopy",
        "pairedStatus": "same_lesion_confirmed",
        "site": "Left cheek",
        "verificationStrength": "license_blocked",
        "verificationMethod": "histopathology",
        "histopathology": "present_figure_caption",
        "dermoscopicTeachingValue": "Not assessed after the license check.",
        "specialSiteValue": "face",
        "status": "rejected_license",
        "reason": "The permissions block links CC BY 4.0 but its text says BY-NC-4.0 and noncommercial use. Unclear terms are rejected even though the case passed the gold and face gates."
      }),
      row({
        "goal": 25,
        "partnerUrl": null,
        "integrated": false,
        "caseId": null,
        "dateChecked": "2026-10-02",
        "thirdPartyExclusion": false,
        "localizationReadiness": null,
        "extraction": [],
        "id": "cand-g25-dpc-small-lm",
        "diagnosisLabel": "Lentigo maligna",
        "sourceLabel": "Dermatology Practical and Conceptual 2021: lentigo maligna less than 1.5 mm",
        "sourceUrl": "https://pmc.ncbi.nlm.nih.gov/articles/PMC7943215/",
        "author": "Saleh",
        "license": "Conflicting: link to CC BY 4.0, text says BY-NC-4.0 noncommercial",
        "modality": "clinical_and_dermoscopy",
        "pairedStatus": "same_lesion_confirmed",
        "site": "Left cheek",
        "verificationStrength": "license_blocked",
        "verificationMethod": "unknown",
        "histopathology": "not_checked",
        "dermoscopicTeachingValue": "Not assessed after the license check.",
        "specialSiteValue": "face",
        "status": "rejected_license",
        "reason": "The same conflicting permissions text as other 2021 issues of the journal. Not downloaded into the case library."
      }),
      row({
        "goal": 25,
        "partnerUrl": null,
        "integrated": false,
        "caseId": null,
        "dateChecked": "2026-10-02",
        "thirdPartyExclusion": false,
        "localizationReadiness": null,
        "extraction": [],
        "id": "cand-g25-dpc-sk-conflict",
        "diagnosisLabel": "Pigmented lesion with conflicting features",
        "sourceLabel": "Dermatology Practical and Conceptual 2021: clinical clues to avoid missing melanoma, Figure 12",
        "sourceUrl": "https://pmc.ncbi.nlm.nih.gov/articles/PMC8480449/",
        "author": "Argenziano and coauthors",
        "license": "Conflicting: link to CC BY 4.0, text says BY-NC-4.0 noncommercial",
        "modality": "clinical_and_dermoscopy",
        "pairedStatus": "same_lesion_confirmed",
        "site": "Not named",
        "verificationStrength": "license_blocked",
        "verificationMethod": "unknown",
        "histopathology": "not_checked",
        "dermoscopicTeachingValue": "Not assessed after the license check.",
        "specialSiteValue": "none",
        "status": "rejected_license",
        "reason": "Conflicting permissions text. A keratosis-versus-melanoma teaching figure, rejected on rights."
      }),
      row({
        "goal": 25,
        "partnerUrl": null,
        "integrated": false,
        "caseId": null,
        "dateChecked": "2026-10-02",
        "thirdPartyExclusion": false,
        "localizationReadiness": null,
        "extraction": [],
        "id": "cand-g25-palmar-pair",
        "diagnosisLabel": "Acral melanoma and acral nevus",
        "sourceLabel": "Diagnostics 2024 iDScore-PalmoPlantar Figure 4: two palmar lesions",
        "sourceUrl": "https://doi.org/10.3390/diagnostics14050460",
        "author": "Linda Tognetti and coauthors, University of Siena",
        "license": "CC BY 4.0",
        "modality": "clinical_and_dermoscopy",
        "pairedStatus": "same_lesion_confirmed",
        "site": "Volar finger and palm",
        "verificationStrength": "histopathology_in_figure_caption",
        "verificationMethod": "histopathology",
        "histopathology": "present_figure_caption",
        "dermoscopicTeachingValue": "Dermoscopic panels are small and blurred; the nevus panel cannot support any structure claim.",
        "specialSiteValue": "acral",
        "status": "rejected_image_quality",
        "reason": "The ideal acral melanoma and acral nevus contrast with histopathology for both, but the dermoscopic panels are about 300 pixels wide and blurred. Pixels were inspected; no structure was defensible on the nevus panel."
      }),
      row({
        "goal": 25,
        "partnerUrl": null,
        "integrated": false,
        "caseId": null,
        "dateChecked": "2026-10-02",
        "thirdPartyExclusion": false,
        "localizationReadiness": null,
        "extraction": [],
        "id": "cand-g25-jdermatol-lm",
        "diagnosisLabel": "Lentigo maligna",
        "sourceLabel": "Journal of Dermatology 2026 Figure 2: representative images of lentigo maligna",
        "sourceUrl": "https://doi.org/10.1111/1346-8138.70238",
        "author": "Authors of the Journal of Dermatology 2026 head and neck imaging study",
        "license": "CC BY 4.0",
        "modality": "clinical_dermoscopy_rcm_histopathology_composite",
        "pairedStatus": "unknown",
        "site": "Head and neck, not named precisely",
        "verificationStrength": "representative_figure",
        "verificationMethod": "unknown",
        "histopathology": "present_figure_caption",
        "dermoscopicTeachingValue": "Gray dots around follicles visible but small.",
        "specialSiteValue": "face",
        "status": "rejected_provenance",
        "reason": "The caption calls the panels representative images and does not say the clinical, dermoscopic, and histologic panels are one lesion. The face site is not named. Not split."
      }),
      row({
        "goal": 25,
        "partnerUrl": null,
        "integrated": false,
        "caseId": null,
        "dateChecked": "2026-10-02",
        "thirdPartyExclusion": false,
        "localizationReadiness": null,
        "extraction": [],
        "id": "cand-g25-jdermatol-pbd",
        "diagnosisLabel": "Pigmented Bowen disease",
        "sourceLabel": "Journal of Dermatology 2026 Figure 1: representative images of pigmented Bowen disease",
        "sourceUrl": "https://doi.org/10.1111/1346-8138.70238",
        "author": "Authors of the Journal of Dermatology 2026 head and neck imaging study",
        "license": "CC BY 4.0",
        "modality": "clinical_dermoscopy_rcm_histopathology_composite",
        "pairedStatus": "unknown",
        "site": "Right cheek",
        "verificationStrength": "representative_figure",
        "verificationMethod": "unknown",
        "histopathology": "present_figure_caption",
        "dermoscopicTeachingValue": "Small panels.",
        "specialSiteValue": "face",
        "status": "rejected_provenance",
        "reason": "Representative-image figure without a same-lesion statement. Not split."
      }),
      row({
        "goal": 25,
        "partnerUrl": null,
        "integrated": false,
        "caseId": null,
        "dateChecked": "2026-10-02",
        "thirdPartyExclusion": false,
        "localizationReadiness": null,
        "extraction": [],
        "id": "cand-g25-jcp-mis-back",
        "diagnosisLabel": "Melanoma in situ",
        "sourceLabel": "Journal of Cutaneous Pathology 2025 Figure 1: melanoma in situ on the upper back",
        "sourceUrl": "https://doi.org/10.1111/cup.14731",
        "author": "Authors of the Journal of Cutaneous Pathology 2025 small melanoma study",
        "license": "CC BY 4.0",
        "modality": "clinical_dermoscopy_rcm_histopathology_composite",
        "pairedStatus": "same_lesion_confirmed",
        "site": "Right upper back",
        "verificationStrength": "histopathology_panels_in_same_figure",
        "verificationMethod": "histopathology",
        "histopathology": "present_figure_caption",
        "dermoscopicTeachingValue": "A drawn outline, arrows, and printed text cover the dermoscopic border.",
        "specialSiteValue": "none",
        "status": "rejected_image_quality",
        "reason": "The clinical panel is a whole shoulder with many brown macules, so the target lesion cannot be located. The dermoscopic panel carries a drawn outline, arrows, and text. Pixels were inspected."
      }),
      row({
        "goal": 25,
        "partnerUrl": null,
        "integrated": false,
        "caseId": null,
        "dateChecked": "2026-10-02",
        "thirdPartyExclusion": false,
        "localizationReadiness": null,
        "extraction": [],
        "id": "cand-g25-abd-micromelanoma",
        "diagnosisLabel": "Melanoma in situ",
        "sourceLabel": "Anais Brasileiros de Dermatologia 2022: small-diameter melanomas, Figure 1",
        "sourceUrl": "https://doi.org/10.1016/j.abd.2020.10.014",
        "author": "Vargas-Mora and coauthors",
        "license": "CC BY 4.0",
        "modality": "clinical_and_dermoscopy",
        "pairedStatus": "same_lesion_confirmed",
        "site": "Not named in the caption",
        "verificationStrength": "not_checked_at_figure_level",
        "verificationMethod": "unknown",
        "histopathology": "not_checked",
        "dermoscopicTeachingValue": "Caption reports an atypical network; pixels not inspected.",
        "specialSiteValue": "none",
        "status": "rejected_redundant",
        "reason": "A small melanoma in situ with an atypical network. That need is filled by the accepted case with histopathology in the caption and a matched benign mimic."
      }),
      row({
        "goal": 25,
        "partnerUrl": null,
        "integrated": false,
        "caseId": null,
        "dateChecked": "2026-10-02",
        "thirdPartyExclusion": false,
        "localizationReadiness": null,
        "extraction": [],
        "id": "cand-g25-abd-dns",
        "diagnosisLabel": "Superficial spreading melanoma and melanoma in situ",
        "sourceLabel": "Anais Brasileiros de Dermatologia 2023: synchronous and metachronous melanomas",
        "sourceUrl": "https://pmc.ncbi.nlm.nih.gov/articles/PMC10334335/",
        "author": "Authors of the 2023 dysplastic nevus syndrome case report",
        "license": "CC BY 4.0",
        "modality": "clinical_and_dermoscopy",
        "pairedStatus": "same_lesion_confirmed",
        "site": "Trunk and lower limb",
        "verificationStrength": "not_checked_at_figure_level",
        "verificationMethod": "unknown",
        "histopathology": "not_checked",
        "dermoscopicTeachingValue": "Captions report atypical network and inverse network; pixels not inspected.",
        "specialSiteValue": "none",
        "status": "rejected_redundant",
        "reason": "Network-type melanoma examples redundant with the accepted pair for this Goal. A possible later source for an inverse network example."
      }),
      row({
        "goal": 25,
        "partnerUrl": null,
        "integrated": false,
        "caseId": null,
        "dateChecked": "2026-10-02",
        "thirdPartyExclusion": false,
        "localizationReadiness": null,
        "extraction": [],
        "id": "cand-g25-cureus-plantar",
        "diagnosisLabel": "Plantar malignant melanoma",
        "sourceLabel": "Cureus 2024: plantar melanoma with pembrolizumab-associated uveitis, Figure 1",
        "sourceUrl": "https://pmc.ncbi.nlm.nih.gov/articles/PMC11636581/",
        "author": "Sugino and coauthors",
        "license": "CC BY 4.0",
        "modality": "clinical_dermoscopy_and_eye_oct_composite",
        "pairedStatus": "same_lesion_confirmed",
        "site": "Right sole",
        "verificationStrength": "not_checked_at_figure_level",
        "verificationMethod": "unknown",
        "histopathology": "not_checked",
        "dermoscopicTeachingValue": "Caption reports parallel ridge pattern; pixels not inspected.",
        "specialSiteValue": "acral",
        "status": "rejected_redundant",
        "reason": "An invasive plantar example with an unrelated eye panel in the same figure. The accepted heel case with study-level pathology covers the parallel ridge exposure for this Goal."
      }),
      row({
        "goal": 25,
        "partnerUrl": null,
        "integrated": false,
        "caseId": null,
        "dateChecked": "2026-10-02",
        "thirdPartyExclusion": false,
        "localizationReadiness": null,
        "extraction": [],
        "id": "cand-g25-melanoacanthoma",
        "diagnosisLabel": "Melanoacanthoma",
        "sourceLabel": "Anais Brasileiros de Dermatologia 2019: melanoacanthoma, Figure 1",
        "sourceUrl": "https://pmc.ncbi.nlm.nih.gov/articles/PMC6939077/",
        "author": "Authors of the 2019 melanoacanthoma report",
        "license": "CC BY 4.0",
        "modality": "clinical_and_dermoscopy",
        "pairedStatus": "same_lesion_confirmed",
        "site": "Right parietal scalp",
        "verificationStrength": "not_checked_at_figure_level",
        "verificationMethod": "unknown",
        "histopathology": "not_checked",
        "dermoscopicTeachingValue": "Caption reports irregular dots and fat fingers; pixels not inspected.",
        "specialSiteValue": "none",
        "status": "candidate",
        "reason": "A pigmented keratosis variant that mimics melanoma. Deferred; histopathology wording and pixels were not checked."
      }),
      row({
        "goal": 25,
        "partnerUrl": null,
        "integrated": false,
        "caseId": null,
        "dateChecked": "2026-10-02",
        "thirdPartyExclusion": false,
        "localizationReadiness": null,
        "extraction": [],
        "id": "cand-g25-lplk-cureus",
        "diagnosisLabel": "Lichen planus-like keratosis",
        "sourceLabel": "Cureus 2025: solitary lichen planus keratosis as a mimic of malignant neoplasm",
        "sourceUrl": "https://pmc.ncbi.nlm.nih.gov/articles/PMC12142276/",
        "author": "Mansour Billah and coauthors",
        "license": "CC BY 4.0",
        "modality": "clinical_and_dermoscopy",
        "pairedStatus": "same_lesion_confirmed",
        "site": "Mid back and upper thigh",
        "verificationStrength": "not_checked_at_figure_level",
        "verificationMethod": "unknown",
        "histopathology": "not_checked",
        "dermoscopicTeachingValue": "Captions report vessels, scale, and shiny white blotches on pink lesions; pixels not inspected.",
        "specialSiteValue": "none",
        "status": "candidate",
        "reason": "LPLK is in the desired facial ecosystem, but these lesions are on the trunk and thigh and are pink rather than pigmented. Deferred."
      }),
      row({
        "goal": 25,
        "partnerUrl": null,
        "integrated": false,
        "caseId": null,
        "dateChecked": "2026-10-02",
        "thirdPartyExclusion": false,
        "localizationReadiness": null,
        "extraction": [],
        "id": "cand-g25-nail-pscc",
        "diagnosisLabel": "Pigmented squamous cell carcinoma in situ of the nail",
        "sourceLabel": "JAAD Case Reports 2025: pigmented SCC in situ of the nail, Figure 1",
        "sourceUrl": "https://pmc.ncbi.nlm.nih.gov/articles/PMC11910622/",
        "author": "Authors of the JAAD Case Reports 2025 nail report",
        "license": "CC BY 4.0",
        "modality": "clinical_and_dermoscopy",
        "pairedStatus": "same_lesion_confirmed",
        "site": "Third right fingernail",
        "verificationStrength": "not_checked_at_figure_level",
        "verificationMethod": "unknown",
        "histopathology": "not_checked",
        "dermoscopicTeachingValue": "Caption reports irregular longitudinal lines; pixels not inspected.",
        "specialSiteValue": "nail",
        "status": "candidate",
        "reason": "A nail mimic of melanoma under a clean CC BY 4.0 text. The clinical panel combines an overview and a detail. Deferred to a nail-focused Goal; pixels not inspected."
      }),
      row({
        "goal": 25,
        "partnerUrl": null,
        "integrated": false,
        "caseId": null,
        "dateChecked": "2026-10-02",
        "thirdPartyExclusion": false,
        "localizationReadiness": null,
        "extraction": [],
        "id": "cand-g25-melanonychia-child",
        "diagnosisLabel": "Longitudinal melanonychia in childhood",
        "sourceLabel": "Anais Brasileiros de Dermatologia 2022: longitudinal melanonychia in childhood, Figure 1",
        "sourceUrl": "https://pmc.ncbi.nlm.nih.gov/articles/PMC9263629/",
        "author": "Authors of the 2022 childhood melanonychia report",
        "license": "CC BY 4.0",
        "modality": "clinical_and_serial_dermoscopy",
        "pairedStatus": "same_lesion_confirmed",
        "site": "Left hallux nail",
        "verificationStrength": "not_checked_at_figure_level",
        "verificationMethod": "unknown",
        "histopathology": "not_checked",
        "dermoscopicTeachingValue": "Serial and intraoperative dermoscopy; pixels not inspected.",
        "specialSiteValue": "nail",
        "status": "candidate",
        "reason": "A nail case whose figure mixes first-visit, intraoperative, and follow-up dermoscopy. Deferred; a follow-up sequence needs a separate design decision."
      }),
      row({
        "goal": 25,
        "partnerUrl": null,
        "integrated": false,
        "caseId": null,
        "dateChecked": "2026-10-02",
        "thirdPartyExclusion": false,
        "localizationReadiness": null,
        "extraction": [],
        "id": "cand-g25-umbilical-nevi",
        "diagnosisLabel": "Umbilical compound and dermal nevi",
        "sourceLabel": "Journal of Clinical Medicine 2024 dermoscopy of umbilical lesions, Figures 3 to 5",
        "sourceUrl": "https://pmc.ncbi.nlm.nih.gov/articles/PMC10970748/",
        "author": "Authors of the 2024 umbilical dermoscopy review",
        "license": "CC BY 4.0",
        "modality": "clinical_and_dermoscopy",
        "pairedStatus": "same_lesion_confirmed",
        "site": "Umbilicus",
        "verificationStrength": "not_checked_at_figure_level",
        "verificationMethod": "unknown",
        "histopathology": "not_checked",
        "dermoscopicTeachingValue": "Captions report globules and structureless areas; pixels not inspected.",
        "specialSiteValue": "none",
        "status": "rejected_teaching_value",
        "reason": "Benign nevi on an unusual site without a stated verification method. They add less than a histopathology-confirmed nevus that shares a melanoma feature."
      }),
      row({
        "goal": 25,
        "partnerUrl": null,
        "integrated": false,
        "caseId": null,
        "dateChecked": "2026-10-02",
        "thirdPartyExclusion": false,
        "localizationReadiness": null,
        "extraction": [],
        "id": "cand-g25-pcmr-acral-nevus",
        "diagnosisLabel": "Acral nevus with parallel furrow pattern",
        "sourceLabel": "Pigment Cell and Melanoma Research 2021 acral melanoma review, Figure 1",
        "sourceUrl": "https://pmc.ncbi.nlm.nih.gov/articles/PMC7818404/",
        "author": "Authors of the 2021 acral lentiginous melanoma review",
        "license": "CC BY 4.0",
        "modality": "clinical_and_dermoscopy_review_composite",
        "pairedStatus": "unknown",
        "site": "Acral",
        "verificationStrength": "review_figure_verification_not_stated",
        "verificationMethod": "unknown",
        "histopathology": "not_checked",
        "dermoscopicTeachingValue": "Caption reports a parallel furrow pattern; pixels not inspected.",
        "specialSiteValue": "acral",
        "status": "candidate",
        "reason": "The benign acral counterpart Docutis needs, but the review figure does not state verification or per-panel provenance. Needs a provenance check before use."
      }),
      row({
        "goal": 25,
        "partnerUrl": null,
        "integrated": false,
        "caseId": null,
        "dateChecked": "2026-10-02",
        "thirdPartyExclusion": false,
        "localizationReadiness": null,
        "extraction": [],
        "id": "cand-g25-dpc-2020-blue-nevus",
        "diagnosisLabel": "Blue nevus",
        "sourceLabel": "Dermatology Practical and Conceptual 2020: congenital melanocytic nevi review, Figure 1",
        "sourceUrl": "https://pmc.ncbi.nlm.nih.gov/articles/PMC7343237/",
        "author": "Argenziano and coauthors",
        "license": "CC BY 4.0",
        "modality": "clinical_and_dermoscopy",
        "pairedStatus": "source_documented_pair",
        "site": "Not named",
        "verificationStrength": "review_figure_verification_not_stated",
        "verificationMethod": "unknown",
        "histopathology": "not_checked",
        "dermoscopicTeachingValue": "Pixels not inspected.",
        "specialSiteValue": "none",
        "status": "candidate",
        "reason": "Unlike the 2021 issues, this permissions text is plain CC BY. A possible second blue nevus example; verification is not stated."
      }),
      row({
        "goal": 25,
        "partnerUrl": null,
        "integrated": false,
        "caseId": null,
        "dateChecked": "2026-10-02",
        "thirdPartyExclusion": false,
        "localizationReadiness": null,
        "extraction": [],
        "id": "cand-g25-commons-rps-nevus",
        "diagnosisLabel": "Intradermal melanocytic nevus",
        "sourceLabel": "Nevus melanocitico intradermico (RPS 09-12-2019) imagen dermatoscopica",
        "sourceUrl": "https://commons.wikimedia.org/wiki/File:Nevus_melanoc%C3%ADtico_intrad%C3%A9rmico_(RPS_09-12-2019)_imagen_dermatosc%C3%B3pica.jpg",
        "author": "Commons uploader RPS",
        "license": "Not checked; no partner found",
        "modality": "dermoscopy",
        "pairedStatus": "not_a_pair",
        "site": "Not named",
        "verificationStrength": "no_clinical_partner",
        "verificationMethod": "unknown",
        "histopathology": "not_checked",
        "dermoscopicTeachingValue": "Not assessed.",
        "specialSiteValue": "none",
        "status": "rejected_not_true_pair",
        "reason": "Commons searches for dermoscopy terms in five languages found this dermoscopic file but no clinical file of the same lesion. Not downloaded."
      })
    ])
  });
})();
