/* Goal 20 reusable pattern library. Educational teaching text. Review required. Not clinician reviewed. A pattern is not a diagnosis. */
(function () {
  "use strict";

  function source(item) {
    return Object.freeze({ ...item });
  }

  const sources = Object.freeze({
    "eado-melanoma-diagnostics-2024": source({
      id: "eado-melanoma-diagnostics-2024",
      title: "European consensus-based interdisciplinary guideline for melanoma. Part 1: Diagnostics — Update 2024",
      organization: "EADO / EDF / EORTC",
      type: "guideline",
      year: 2025,
      version: "2024 update; part 1",
      url: "https://pubmed.ncbi.nlm.nih.gov/39700658/",
      doi: "10.1016/j.ejca.2024.115152",
      metadataCheckedAt: "2026-09-20"
    }),
    "s2k-bcc-2024": source({
      id: "s2k-bcc-2024",
      title: "S2k-Leitlinie Basalzellkarzinom der Haut",
      organization: "German Dermatological Society guideline group / AWMF 032-021",
      type: "guideline",
      year: 2024,
      version: "9.0; AWMF 032-021",
      url: "https://register.awmf.org/assets/guidelines/032-021l_S2k_Basalzellkarzinom-der-Haut_2024-07.pdf",
      doi: null,
      metadataCheckedAt: "2026-09-23"
    }),
    "ka-review-2021": source({
      id: "ka-review-2021",
      title: "Keratoacanthoma: Update on the Debate",
      organization: "American Journal of Dermatopathology",
      type: "peer-reviewed review",
      year: 2021,
      url: "https://pubmed.ncbi.nlm.nih.gov/33395044/",
      doi: "10.1097/DAD.0000000000001872",
      metadataCheckedAt: "2026-09-15"
    }),
    "docutis-case-constraint-2026": source({
      id: "docutis-case-constraint-2026",
      title: "Docutis case observation already stored on the linked case",
      organization: "Docutis",
      type: "project-teaching-note",
      year: 2026,
      url: "https://github.com/mnasuharas/Docutis",
      doi: null,
      metadataCheckedAt: "2026-10-01"
    })
  });

  function pat(item) {
    return Object.freeze({
      id: item.id,
      displayName: item.displayName,
      displayNameDe: item.displayNameDe || null,
      internationalTerm: item.internationalTerm || null,
      aliases: Object.freeze(item.aliases || []),
      modality: item.modality,
      category: item.category,
      definition: item.definition,
      lookFor: item.lookFor,
      morphologyClues: Object.freeze(item.morphologyClues || []),
      commonContexts: Object.freeze(item.commonContexts || []),
      malignantAssociations: Object.freeze(item.malignantAssociations || []),
      benignAssociations: Object.freeze(item.benignAssociations || []),
      mimics: Object.freeze(item.mimics || []),
      traps: Object.freeze(item.traps || []),
      doesNotProve: Object.freeze(item.doesNotProve || []),
      usualRole: item.usualRole,
      sourceIds: Object.freeze(item.sourceIds),
      supports: item.supports,
      limitsOfClaim: item.limitsOfClaim,
      relatedPatternIds: Object.freeze(item.relatedPatternIds || []),
      reviewStatus: "clinician review required",
      clinicalReview: null
    });
  }

  const patterns = [
    pat({
      id: "asymmetric-thickness",
      displayName: "Asymmetric thickness",
      displayNameDe: "Asymmetrische Dicke",
      modality: "clinical",
      category: "clinical-morphology",
      definition: "One half of a lesion looks thicker than the other half. The cutaneous melanoma record lists asymmetry among suspicious clinical features.",
      lookFor: "Compare the two halves. Say which half is thicker before you name a diagnosis.",
      morphologyClues: ["A thicker half", "Thickness is the comparison, even when the outline is also uneven"],
      commonContexts: ["A single dark raised lesion on a clinical photograph"],
      malignantAssociations: ["The melanoma record treats asymmetry as a suspicious feature, not as a completed diagnosis."],
      benignAssociations: ["A benign raised lesion can be asymmetric. No benign case in this library encodes this pattern."],
      mimics: ["Pigmented keratinocyte tumor"],
      traps: ["Treating a thicker half as proof, or inventing a millimeter reading because a scale is in the frame."],
      doesNotProve: ["It does not prove a melanocytic diagnosis.", "It does not prove a thickness in millimeters.", "It does not prove a histologic subtype or a stage."],
      usualRole: "context-dependent",
      sourceIds: ["eado-melanoma-diagnostics-2024"],
      supports: "The cutaneous melanoma record, which already cites the EADO 2024 diagnostics guideline, lists asymmetry as a suspicious clinical feature. This text does not add a probability.",
      limitsOfClaim: "The guideline is cited only for that existing record sentence. It is not cited for a performance figure or for this photograph.",
      relatedPatternIds: ["notched-border", "color-variegation"]
    }),
    pat({
      id: "notched-border",
      displayName: "Notched border",
      displayNameDe: "Gekerbter Rand",
      modality: "clinical",
      category: "clinical-morphology",
      definition: "The edge is not a smooth oval. A notch is a bite out of the outline. The melanoma record lists border irregularity as a suspicious feature.",
      lookFor: "Trace the edge and point to the notch before you name a diagnosis.",
      morphologyClues: ["A notch or step in the outline"],
      commonContexts: ["A small dark lesion on a clinical photograph"],
      malignantAssociations: ["Border irregularity is a suspicious feature on the melanoma record. It is not specific."],
      benignAssociations: ["A benign pigmented lesion can have an uneven edge. No benign case in this library encodes this pattern."],
      mimics: ["Seborrheic keratosis"],
      traps: ["Calling every uneven edge one diagnosis."],
      doesNotProve: ["It does not prove a melanocytic diagnosis.", "It does not name the closest mimic by itself."],
      usualRole: "context-dependent",
      sourceIds: ["eado-melanoma-diagnostics-2024"],
      supports: "The cutaneous melanoma record, citing the EADO 2024 diagnostics guideline, lists border irregularity as a suspicious clinical feature.",
      limitsOfClaim: "No new border criterion is added beyond that record sentence and the linked case note.",
      relatedPatternIds: ["asymmetric-thickness", "color-variegation"]
    }),
    pat({
      id: "color-variegation",
      displayName: "More than one dark color",
      displayNameDe: "Mehrere dunkle Farben",
      internationalTerm: "Color variegation",
      aliases: ["Several dark colors"],
      modality: "clinical",
      category: "clinical-morphology",
      definition: "Two or more dark colors sit in the same lesion. The melanoma record lists color variation as a suspicious feature. Colors you cannot see are not part of the finding.",
      lookFor: "Name only the colors in the frame. Do not invent a count.",
      morphologyClues: ["More than one dark hue in one lesion"],
      commonContexts: ["A dark clinical lesion whose colors are uneven"],
      malignantAssociations: ["Color variation is a suspicious feature on the melanoma record. It is not specific."],
      benignAssociations: ["Benign pigmented lesions can hold more than one color. No benign case in this library encodes this pattern."],
      mimics: ["Seborrheic keratosis"],
      traps: ["Turning a color mix into a probability, or naming colors that are not in the frame."],
      doesNotProve: ["It does not prove a melanocytic diagnosis.", "It does not count colors beyond what you can see."],
      usualRole: "context-dependent",
      sourceIds: ["eado-melanoma-diagnostics-2024"],
      supports: "The cutaneous melanoma record, citing the EADO 2024 diagnostics guideline, lists color variation as a suspicious clinical feature.",
      limitsOfClaim: "The citation does not support a number of colors or a diagnostic percentage.",
      relatedPatternIds: ["peripheral-dark-focus", "notched-border"]
    }),
    pat({
      id: "broad-brown-patch",
      displayName: "Broad uneven brown patch",
      modality: "clinical",
      category: "clinical-morphology",
      definition: "A wide brown patch whose color or edge is uneven. The melanoma record describes variable pigmentation and an irregular border. The patch is not a stage and not a body site.",
      lookFor: "Say whether the patch is broad and whether the brown is even.",
      morphologyClues: ["A broad brown area rather than a small papule"],
      commonContexts: ["A flat or slightly raised brown patch"],
      malignantAssociations: ["Uneven brown pigment is a suspicious look on the melanoma record. Site and subtype are not given by the shape."],
      benignAssociations: ["A solar lentigo is the closest mimic stored on the linked case. No solar lentigo case is in the library."],
      mimics: ["Solar lentigo"],
      traps: ["Reading a broad patch as a stage, a subtype, or a named site."],
      doesNotProve: ["It does not prove a subtype.", "It does not prove the anatomic site.", "It does not prove a histologic diagnosis."],
      usualRole: "context-dependent",
      sourceIds: ["eado-melanoma-diagnostics-2024"],
      supports: "The melanoma record lists variable pigmentation and an irregular border. The linked case says site and subtype are not in the caption.",
      limitsOfClaim: "Nothing here assigns lentigo maligna, a diameter, or a stage.",
      relatedPatternIds: ["irregular-brown-patch", "peripheral-dark-focus"]
    }),
    pat({
      id: "peripheral-dark-focus",
      displayName: "Darker focus at one edge",
      modality: "clinical",
      category: "clinical-morphology",
      definition: "One part of the edge is darker than the rest of the patch. It is a color finding, not a measurement and not a subtype.",
      lookFor: "Point to the darker edge. Do not give it a histologic name.",
      morphologyClues: ["A darker area at the periphery"],
      commonContexts: ["An uneven brown patch"],
      malignantAssociations: ["Uneven color supports concern. It does not name a tumor."],
      benignAssociations: ["The linked case names solar lentigo as the closest mimic. No solar lentigo case is encoded."],
      mimics: ["Solar lentigo"],
      traps: ["Calling the darker edge a subtype or a measured focus."],
      doesNotProve: ["It does not prove a subtype.", "It does not prove a measurement."],
      usualRole: "context-dependent",
      sourceIds: ["eado-melanoma-diagnostics-2024", "docutis-case-constraint-2026"],
      supports: "Color variation is the melanoma record's suspicious feature. The linked case already limits this finding to uneven color.",
      limitsOfClaim: "The case weight stays on the case. This definition does not raise it.",
      relatedPatternIds: ["color-variegation", "broad-brown-patch"]
    }),
    pat({
      id: "pale-center",
      displayName: "Pale center inside a darker rim",
      modality: "clinical",
      category: "clinical-morphology",
      definition: "The middle of a pigmented lesion is paler than the rim. Pallor is a color finding. It is not a histologic process.",
      lookFor: "See whether the center is lighter than the rim. Do not rename the pale area.",
      morphologyClues: ["A lighter center and a darker rim"],
      commonContexts: ["A brown clinical lesion with central pallor"],
      malignantAssociations: ["Pallor can sit inside a suspicious pigmented lesion. It is not a diagnosis."],
      benignAssociations: ["The linked case names an inflamed benign lesion as a possible mimic. No such case is encoded."],
      mimics: ["Lichenoid keratosis or inflamed benign lesion"],
      traps: ["Giving the pale center a histologic name the source did not use."],
      doesNotProve: ["It does not prove regression.", "It does not prove inflammation.", "It does not prove a diagnosis."],
      usualRole: "context-dependent",
      sourceIds: ["docutis-case-constraint-2026", "eado-melanoma-diagnostics-2024"],
      supports: "The linked case states that pallor is not a histologic name. The melanoma record does not let color alone complete a diagnosis.",
      limitsOfClaim: "Regression is not asserted. The source title did not give the pale center a histologic name.",
      relatedPatternIds: []
    }),
    pat({
      id: "nodule-beside-pigmented-macule",
      displayName: "Nodule touching a pigmented macule",
      modality: "clinical",
      category: "clinical-morphology",
      definition: "A raised lesion and a flatter pigmented area touch. The silhouette is a combined shape. The source, not the shape, assigns the names.",
      lookFor: "See whether the raised part and the flat pigmented part touch. Ignore marker ink.",
      morphologyClues: ["A nodule in contact with a darker flat area"],
      commonContexts: ["A combined clinical lesion"],
      malignantAssociations: ["A combined raised and flat pigmented lesion is concerning until the source is read. The shape is not specific."],
      benignAssociations: ["No benign combined lesion is encoded."],
      mimics: ["Nodular basal cell carcinoma"],
      traps: ["Naming the two parts from the silhouette, or tracing marker ink as skin."],
      doesNotProve: ["It does not prove which part is which diagnosis.", "It does not prove a subtype."],
      usualRole: "context-dependent",
      sourceIds: ["docutis-case-constraint-2026", "eado-melanoma-diagnostics-2024"],
      supports: "The linked case already says the combination is concerning and not specific until the source is read.",
      limitsOfClaim: "No Breslow thickness and no subtype are added.",
      relatedPatternIds: ["flat-area-with-raised-focus"]
    }),
    pat({
      id: "flat-area-with-raised-focus",
      displayName: "Flat area with a raised dark focus",
      modality: "clinical",
      category: "clinical-morphology",
      definition: "A flatter area and a raised darker focus sit together. A gray zone, when present, is a color. It is not a histologic word.",
      lookFor: "Separate the flat area, the raised focus, and any printed arrow.",
      morphologyClues: ["Flat pigment beside a raised darker focus"],
      commonContexts: ["A clinical photograph that may already contain a printed arrow"],
      malignantAssociations: ["The combination is a suspicious clinical look. The source assigns the names."],
      benignAssociations: ["No benign case encodes this combined look."],
      mimics: ["Pigmented basal cell carcinoma"],
      traps: ["Reading a printed arrow as a skin finding, or renaming gray color as a histologic structure."],
      doesNotProve: ["It does not prove a subtype.", "It does not prove what the gray area is."],
      usualRole: "context-dependent",
      sourceIds: ["eado-melanoma-diagnostics-2024", "docutis-case-constraint-2026"],
      supports: "The melanoma record, citing the EADO 2024 diagnostics guideline, does not let a silhouette alone complete a diagnosis. The linked case already separates the visible combination from a histologic word for the gray area.",
      limitsOfClaim: "This does not add a dermoscopic structure the photograph does not record.",
      relatedPatternIds: ["nodule-beside-pigmented-macule"]
    }),
    pat({
      id: "solitary-dark-papule",
      displayName: "Solitary dark papule",
      modality: "clinical",
      category: "clinical-morphology",
      definition: "One dark raised papule. A single frame does not show whether it changed.",
      lookFor: "Describe the papule in the frame. Do not describe an earlier photograph that is not there.",
      morphologyClues: ["A single dark papule"],
      commonContexts: ["A clinical close-up without a prior image"],
      malignantAssociations: ["A dark papule can be suspicious. Change over time is not visible here."],
      benignAssociations: ["The linked case names an inflamed or traumatized nevus as the closest mimic. No nevus case is encoded."],
      mimics: ["Inflamed or traumatized nevus"],
      traps: ["Seeing change in one photograph."],
      doesNotProve: ["It does not prove growth.", "It does not prove a melanocytic diagnosis."],
      usualRole: "context-dependent",
      sourceIds: ["docutis-case-constraint-2026", "eado-melanoma-diagnostics-2024"],
      supports: "The melanoma record lists evolution as a suspicious feature when there is a history. The linked case says this file does not show that change.",
      limitsOfClaim: "Evolution is not claimed from this frame.",
      relatedPatternIds: ["change-outside-one-frame"]
    }),
    pat({
      id: "irregular-brown-patch",
      displayName: "Irregular brown patch",
      modality: "clinical",
      category: "clinical-morphology",
      definition: "A brown patch with an irregular edge. One frame does not show a change in diameter.",
      lookFor: "Trace the brown edge. Do not invent a second date.",
      morphologyClues: ["An irregular brown patch"],
      commonContexts: ["A single clinical photograph beside a skin crease or on unnamed skin"],
      malignantAssociations: ["An irregular brown patch is a suspicious look on the melanoma record. It is not specific."],
      benignAssociations: ["Seborrheic keratosis is the closest mimic on the linked case. No seborrheic keratosis case is encoded."],
      mimics: ["Seborrheic keratosis"],
      traps: ["Treating one frame as proof that the diameter changed."],
      doesNotProve: ["It does not prove growth.", "It does not prove a diagnosis."],
      usualRole: "context-dependent",
      sourceIds: ["eado-melanoma-diagnostics-2024", "docutis-case-constraint-2026"],
      supports: "Border irregularity is the melanoma record's suspicious feature. The linked case says change in size is not visible in one frame.",
      limitsOfClaim: "No diameter and no second date are added.",
      relatedPatternIds: ["broad-brown-patch", "change-outside-one-frame"]
    }),
    pat({
      id: "pink-nodule-without-pigment",
      displayName: "Pink nodule without brown pigment",
      displayNameDe: "Rosa Knoten ohne braunes Pigment",
      modality: "clinical",
      category: "clinical-morphology",
      definition: "A pink or red nodule without brown pigment in the frame. The melanoma record states that some melanomas are amelanotic. Lack of brown pigment is not reassuring and is not specific.",
      lookFor: "Say whether brown pigment is visible. If it is not, say so, and do not turn that absence into a diagnosis by itself.",
      morphologyClues: ["A pink or red nodule", "No brown pigment in the frame"],
      commonContexts: ["A clinical photograph of a solitary pink nodule"],
      malignantAssociations: ["The melanoma record says some melanomas are amelanotic. The BCC record describes pearly or erythematous papules and nodules."],
      benignAssociations: ["No benign pink nodule is encoded."],
      mimics: ["Nodular basal cell carcinoma"],
      traps: ["Feeling reassured because brown pigment is absent."],
      doesNotProve: ["It does not prove an amelanotic melanocytic tumor.", "It does not prove a basal cell carcinoma."],
      usualRole: "context-dependent",
      sourceIds: ["eado-melanoma-diagnostics-2024", "s2k-bcc-2024"],
      supports: "The melanoma record says some melanomas are amelanotic. The BCC record describes an erythematous papule or nodule. Neither sentence is a probability.",
      limitsOfClaim: "Amelanotic is a source diagnosis on the linked case, not a conclusion from the color word alone.",
      relatedPatternIds: ["shiny-red-papule", "pink-scaly-spot"]
    }),
    pat({
      id: "polymorphous-vessels",
      displayName: "More than one vessel shape",
      displayNameDe: "Polymorphe Gefäße",
      internationalTerm: "Polymorphous vessels",
      aliases: ["Dotted and linear vessels together"],
      modality: "dermoscopic",
      category: "dermoscopic-structure",
      definition: "Dotted and linear vessels are both present in the same dermoscopic field. The melanoma record lists atypical vessels as a high-risk clue. Mixed vessels are not specific for one tumor.",
      lookFor: "Name the vessel shapes you can see. Ignore printed circles and scales.",
      morphologyClues: ["More than one red vessel shape"],
      commonContexts: ["A pink dermoscopic field"],
      malignantAssociations: ["Atypical vessels are a high-risk clue on the melanoma record. The BCC record lists different vessel words, including arborising vessels."],
      benignAssociations: ["No benign case encodes mixed vessels."],
      mimics: ["Basal cell carcinoma"],
      traps: ["Renaming mixed vessels as arborizing vessels, or reading a printed circle as a shiny line."],
      doesNotProve: ["It does not prove one tumor.", "It does not prove a probability."],
      usualRole: "context-dependent",
      sourceIds: ["eado-melanoma-diagnostics-2024", "s2k-bcc-2024"],
      supports: "The melanoma record lists atypical vessels. The BCC record lists arborising vessels as a separate supportive finding. The two phrases are not interchangeable.",
      limitsOfClaim: "No vessel count and no performance figure are added.",
      relatedPatternIds: ["arborizing-vessels", "surface-vessels"]
    }),
    pat({
      id: "nail-plate-destruction",
      displayName: "Destroyed nail plate",
      displayNameDe: "Zerstörte Nagelplatte",
      modality: "clinical",
      category: "clinical-morphology",
      definition: "The nail plate is broken, missing, or covered by dark debris. The acral melanoma record says nail findings need site-specific assessment. Destruction is not specific for a melanocytic tumor.",
      lookFor: "Describe the plate and the debris. Do not add a streak on the fold if you cannot see one.",
      morphologyClues: ["A damaged nail plate", "Dark debris"],
      commonContexts: ["The thumb nail unit or another nail unit"],
      malignantAssociations: ["Nail-unit melanoma is a reason for site-specific assessment. Keratinocyte tumors of the nail unit remain possible."],
      benignAssociations: ["No benign nail case is encoded."],
      mimics: ["Nail-unit squamous cell carcinoma or other keratinocyte tumor"],
      traps: ["Calling nail destruction a melanocytic diagnosis, or inventing a streak."],
      doesNotProve: ["It does not prove a melanocytic tumor.", "It does not prove a streak you cannot see."],
      usualRole: "context-dependent",
      sourceIds: ["eado-melanoma-diagnostics-2024", "docutis-case-constraint-2026"],
      supports: "The Docutis acral melanoma record, which cites the EADO 2024 diagnostics guideline, states that nail findings require site-specific assessment. This text does not quote a new page.",
      limitsOfClaim: "No Hutchinson sign is named. The linked case does not claim a fold streak.",
      relatedPatternIds: ["pigmented-nail-streak"]
    }),
    pat({
      id: "pigmented-nail-streak",
      displayName: "Pigmented streak on the nail fold",
      modality: "clinical",
      category: "clinical-morphology",
      definition: "A dark streak on the nail fold is a site-specific nail finding. The only nail case in this library records that a clear streak is not claimed from that frame.",
      lookFor: "Look at the fold. If you cannot see a streak, do not supply one.",
      morphologyClues: ["A dark streak on the nail fold, only when it is visible"],
      commonContexts: ["Nail-unit photographs"],
      malignantAssociations: ["A fold streak can matter in nail-unit assessment. A streak that is not visible does not establish a nail-unit melanoma."],
      benignAssociations: ["Blood or a benign pigment can also color a nail fold. No benign nail case is encoded."],
      mimics: ["Nail-unit squamous cell carcinoma or other keratinocyte tumor"],
      traps: ["Supplying a streak the frame does not show."],
      doesNotProve: ["An absent streak does not prove a diagnosis.", "An absent streak does not prove that the nail is safe."],
      usualRole: "context-dependent",
      sourceIds: ["eado-melanoma-diagnostics-2024", "docutis-case-constraint-2026"],
      supports: "Nail findings need site-specific assessment in the acral melanoma record. The linked case says a clear fold streak is not claimed.",
      limitsOfClaim: "The pattern is not marked present. Case certainty stays not visible.",
      relatedPatternIds: ["nail-plate-destruction"]
    }),
    pat({
      id: "pink-scaly-spot",
      displayName: "Small pink scaly spot",
      modality: "clinical",
      category: "clinical-morphology",
      definition: "A small pink spot with scale. The BCC record says superficial BCC usually presents as an erythematous macule or thin plaque. Scale on a small pink spot is not specific.",
      lookFor: "Note the size, the pink color, and whether scale is actually visible.",
      morphologyClues: ["Small", "Pink", "Scale, when you can see it"],
      commonContexts: ["A small clinical spot on unnamed skin"],
      malignantAssociations: ["Superficial BCC is the description on the BCC record. The melanoma record says some melanomas are amelanotic, so a pink spot is not automatically a keratinocyte tumor."],
      benignAssociations: ["A dermatitis can scale. No dermatitis case encodes this pattern."],
      mimics: ["Amelanotic melanoma"],
      traps: ["Treating scale as specific."],
      doesNotProve: ["It does not prove a basal cell carcinoma.", "It does not prove a melanocytic tumor."],
      usualRole: "nonspecific",
      sourceIds: ["s2k-bcc-2024", "eado-melanoma-diagnostics-2024"],
      supports: "The BCC record describes superficial BCC as an erythematous macule or thin plaque. The melanoma record says some melanomas are amelanotic.",
      limitsOfClaim: "No dermoscopic vessels were added to the clinical case.",
      relatedPatternIds: ["small-erosion", "pink-nodule-without-pigment"]
    }),
    pat({
      id: "small-erosion",
      displayName: "Small erosion",
      displayNameDe: "Kleine Erosion",
      modality: "clinical",
      category: "clinical-morphology",
      definition: "A small break in the surface. The BCC record lists erosion or ulcer as a possible secondary change, and says ulceration alone is not a high recurrence-risk criterion.",
      lookFor: "Point to the break in the surface and to the site you can actually see.",
      morphologyClues: ["A small surface break"],
      commonContexts: ["Sun-exposed skin such as the ear, when the case names that site"],
      malignantAssociations: ["Erosion fits the BCC record's secondary changes. It is not specific, and it is not by itself a high-risk criterion in that record."],
      benignAssociations: ["No benign eroded case is encoded."],
      mimics: ["Amelanotic melanoma"],
      traps: ["Calling every red mark an ulcer, or treating erosion as a risk score."],
      doesNotProve: ["It does not prove a basal cell carcinoma.", "It does not prove a recurrence risk."],
      usualRole: "nonspecific",
      sourceIds: ["s2k-bcc-2024"],
      supports: "The BCC record lists erosion or ulcer and states that ulceration alone is not an S2k Table 2 high recurrence-risk criterion.",
      limitsOfClaim: "The citation is the existing record sentence. No new risk category is added.",
      relatedPatternIds: ["pink-scaly-spot"]
    }),
    pat({
      id: "shiny-red-papule",
      displayName: "Solitary shiny red papule",
      modality: "clinical",
      category: "clinical-morphology",
      definition: "One shiny red papule. The BCC record describes nodular BCC as a pearly or erythematous papule or nodule, often with telangiectasia. Shine alone is not that full description.",
      lookFor: "Say whether the papule is solitary and shiny. Count vessels only if you see them.",
      morphologyClues: ["Solitary", "Shiny", "Red"],
      commonContexts: ["A clinical papule on hair-bearing skin"],
      malignantAssociations: ["A shiny red papule fits the broad BCC description and also the amelanotic melanoma trap named on the linked case."],
      benignAssociations: ["No benign red papule is encoded."],
      mimics: ["Amelanotic melanoma"],
      traps: ["Assuming vessels you have not seen, or feeling specific because the papule is shiny."],
      doesNotProve: ["It does not prove a basal cell carcinoma.", "It does not prove vessels."],
      usualRole: "nonspecific",
      sourceIds: ["s2k-bcc-2024", "eado-melanoma-diagnostics-2024"],
      supports: "The BCC record describes a pearly or erythematous papule or nodule. The melanoma record says some melanomas are amelanotic.",
      limitsOfClaim: "Telangiectasia is not copied onto a case that left vessels uncertain.",
      relatedPatternIds: ["surface-vessels", "pink-nodule-without-pigment"]
    }),
    pat({
      id: "surface-vessels",
      displayName: "Surface vessels",
      displayNameDe: "Oberflächliche Gefäße",
      modality: "both",
      category: "dermoscopic-structure",
      definition: "Red linear, branching, or fine vessels on the surface of a papule or plaque. The BCC record lists arborising vessels and short fine telangiectasias as supportive dermoscopic findings. A clinical photograph does not automatically show them.",
      lookFor: "Count a vessel only when you can see it. A caption that mentions vessels is not a vessel you have confirmed.",
      morphologyClues: ["A red line or branch you can actually trace"],
      commonContexts: ["Clinical or dermoscopic views of a papule"],
      malignantAssociations: ["When the vessels are the arborising form, the BCC record calls them supportive. They are not proof, and they are not specific for one tumor."],
      benignAssociations: ["No benign case encodes surface vessels."],
      mimics: ["A pink nodule without brown pigment can also be vascular. An uncertain or absent vessel does not settle that comparison."],
      traps: ["Upgrading an uncertain or invisible vessel into a clearly visible clue."],
      doesNotProve: ["It does not prove a basal cell carcinoma.", "It does not prove that vessels are present when the case says they are uncertain or not visible."],
      usualRole: "supportive",
      sourceIds: ["s2k-bcc-2024", "docutis-case-constraint-2026"],
      supports: "The BCC record calls arborising vessels and short fine telangiectasias supportive dermoscopic findings, and says dermoscopy does not replace histopathology.",
      limitsOfClaim: "usualRole supportive is the record's general statement. It is not the weight of a linked case. Linked cases currently mark vessels uncertain or not visible.",
      relatedPatternIds: ["arborizing-vessels", "telangiectasia", "shiny-red-papule"]
    }),
    pat({
      id: "crateriform-center",
      displayName: "Crater or central plug",
      displayNameDe: "Krater oder zentraler Hornpfropf",
      modality: "clinical",
      category: "clinical-morphology",
      definition: "A red nodule with a central keratin plug or crater. The keratoacanthoma record describes a dome-shaped nodule with a central keratin-filled crater, and says overlap with squamous cell carcinoma is substantial.",
      lookFor: "Look for a central plug or crater. If the photograph is soft, keep the certainty the case already stored.",
      morphologyClues: ["A central plug or crater in a red nodule"],
      commonContexts: ["A clinical nodule, often with limited detail"],
      malignantAssociations: ["The disease record keeps the relationship to squamous cell carcinoma debated. The linked case also keeps a melanocytic nodule in the differential."],
      benignAssociations: ["The disease record does not classify this tumor as benign."],
      mimics: ["Nodular melanoma"],
      traps: ["Calling a soft crater definite, or using the crater to exclude a melanocytic nodule."],
      doesNotProve: ["It does not separate a keratinizing tumor from a melanocytic nodule.", "It does not show growth speed."],
      usualRole: "context-dependent",
      sourceIds: ["ka-review-2021", "docutis-case-constraint-2026"],
      supports: "The keratoacanthoma record, citing the 2021 review, describes a crateriform nodule and substantial overlap with squamous cell carcinoma. Growth speed is not visible in one frame.",
      limitsOfClaim: "The linked case certainty is probably, not clearly visible. This definition does not upgrade it. Rapid growth is not claimed from the photograph.",
      relatedPatternIds: []
    }),
    pat({
      id: "arborizing-vessels",
      displayName: "Arborizing vessels",
      displayNameDe: "Arborisierende Gefäße",
      internationalTerm: "Arborising vessels",
      aliases: ["Branching vessels"],
      modality: "dermoscopic",
      category: "dermoscopic-structure",
      definition: "Branching red vessels on a translucent field. The BCC record lists arborising vessels as a supportive dermoscopic finding. They can raise confidence and do not replace histopathology.",
      lookFor: "Follow a vessel that branches. Do not call every red line this pattern.",
      morphologyClues: ["A branching red vessel"],
      commonContexts: ["Dermoscopic view of a nodular lesion"],
      malignantAssociations: ["The BCC record lists arborising vessels as supportive for basal cell carcinoma. They are not proof."],
      benignAssociations: ["No benign case encodes arborizing vessels."],
      mimics: ["Other pink tumors can show vessels. The record says dermoscopy does not replace histopathology."],
      traps: ["Treating branching vessels as a completed diagnosis, or ignoring them because the pilot case stored no Goal 19 weight."],
      doesNotProve: ["It does not replace histopathology.", "It does not assign a case weight the case did not store."],
      usualRole: "supportive",
      sourceIds: ["s2k-bcc-2024"],
      supports: "The BCC record lists arborising vessels as a supportive dermoscopic finding and says dermoscopy does not replace histopathology.",
      limitsOfClaim: "The pilot case records the feature token and does not store certainty or weight. usualRole is not that missing weight.",
      relatedPatternIds: ["telangiectasia", "surface-vessels", "polymorphous-vessels"]
    }),
    pat({
      id: "telangiectasia",
      displayName: "Telangiectasia",
      displayNameDe: "Teleangiektasien",
      modality: "both",
      category: "dermoscopic-structure",
      definition: "Fine dilated vessels. The BCC record lists short fine telangiectasias separately from arborising vessels.",
      lookFor: "Separate fine vessels from a branching trunk when both words are recorded. Do not merge them.",
      morphologyClues: ["Short fine red vessels"],
      commonContexts: ["Clinical or dermoscopic views of a nodular lesion"],
      malignantAssociations: ["Short fine telangiectasias are a supportive BCC finding on the record. They are not proof."],
      benignAssociations: ["No benign case encodes telangiectasia as a case pattern."],
      mimics: ["Fine vessels are not specific for one tumor."],
      traps: ["Using telangiectasia and arborizing vessels as if they were the same sentence."],
      doesNotProve: ["It does not prove a basal cell carcinoma.", "It does not prove a case weight."],
      usualRole: "supportive",
      sourceIds: ["s2k-bcc-2024"],
      supports: "The BCC record lists short fine telangiectasias separately from arborising vessels.",
      limitsOfClaim: "The pilot token has no Goal 19 certainty. Do not mark it clearly visible.",
      relatedPatternIds: ["arborizing-vessels", "surface-vessels"]
    }),
    pat({
      id: "maple-leaf-like-areas",
      displayName: "Maple-leaf-like areas",
      displayNameDe: "Ahornblattartige Areale",
      internationalTerm: "Maple leaf-like areas",
      modality: "dermoscopic",
      category: "dermoscopic-structure",
      definition: "Brown leaf-shaped pigment at the edge. The BCC record lists maple leaf-like areas as a pigment structure. They are not a pigment network.",
      lookFor: "Look for a leaf-shaped brown structure. Do not call a network a leaf.",
      morphologyClues: ["Leaf-shaped brown pigment"],
      commonContexts: ["Dermoscopic view of a pigmented lesion"],
      malignantAssociations: ["The BCC record lists this structure for pigmented basal cell carcinoma. Features that suggest melanoma still need clinicopathologic correlation, in the same record."],
      benignAssociations: ["No benign pigmented case encodes this structure."],
      mimics: ["A melanocytic pigment network is a different structure."],
      traps: ["Calling a network a leaf, or treating the leaf as proof."],
      doesNotProve: ["It does not replace histopathology.", "It does not assign a case weight the pilot did not store."],
      usualRole: "supportive",
      sourceIds: ["s2k-bcc-2024"],
      supports: "The BCC record lists maple leaf-like areas among pigment structures and says melanoma-suggesting features need clinicopathologic correlation.",
      limitsOfClaim: "The pilot token is unrated. usualRole supportive is not a certainty.",
      relatedPatternIds: ["blue-gray-ovoid-nests"]
    }),
    pat({
      id: "blue-gray-ovoid-nests",
      displayName: "Blue-gray ovoid nests",
      displayNameDe: "Blaugraue ovaläre Nester",
      internationalTerm: "Blue-grey ovoid nests",
      aliases: ["Blue-gray pigment aggregates"],
      modality: "dermoscopic",
      category: "dermoscopic-structure",
      definition: "Oval blue-gray pigment aggregates. The BCC record lists blue-grey ovoid nests as a pigment structure.",
      lookFor: "Look for a discrete oval blue-gray nest, not a vague dark color.",
      morphologyClues: ["An oval blue-gray aggregate"],
      commonContexts: ["Dermoscopic view of a pigmented lesion"],
      malignantAssociations: ["The BCC record lists blue-grey ovoid nests as a pigment structure of pigmented basal cell carcinoma."],
      benignAssociations: ["No benign case encodes this structure."],
      mimics: ["Other blue-gray pigment, including melanocytic structures, still needs the case differential. This pattern does not close it."],
      traps: ["Naming a nest you cannot outline."],
      doesNotProve: ["It does not replace histopathology.", "It does not prove the pilot certainty, because none was stored."],
      usualRole: "supportive",
      sourceIds: ["s2k-bcc-2024"],
      supports: "The BCC record lists blue-grey ovoid nests as a pigment structure.",
      limitsOfClaim: "No performance figure is added. The pilot case does not store Goal 19 certainty.",
      relatedPatternIds: ["maple-leaf-like-areas"]
    }),
    pat({
      id: "change-outside-one-frame",
      displayName: "Change outside this frame",
      modality: "none",
      category: "observation-limit",
      definition: "A narrative may say a lesion changed. This file does not contain the earlier look or a second date.",
      lookFor: "Separate the source sentence from the single photograph.",
      morphologyClues: ["There is no second image to compare"],
      commonContexts: ["A case whose caption mentions change and whose file has one date"],
      malignantAssociations: ["The melanoma record lists evolution as a suspicious feature when the history is real. This pattern is the missing comparison, not the evolution itself."],
      benignAssociations: ["A benign lesion can also change. No second photograph is encoded."],
      mimics: [],
      traps: ["Seeing change in a file that has only one date."],
      doesNotProve: ["It does not prove growth.", "It does not prove stability."],
      usualRole: "nonspecific",
      sourceIds: ["docutis-case-constraint-2026", "eado-melanoma-diagnostics-2024"],
      supports: "The melanoma record lists evolution as a clinical concern. The linked cases already say the earlier look is not in the file.",
      limitsOfClaim: "No interval and no millimeter change are invented.",
      relatedPatternIds: ["solitary-dark-papule", "irregular-brown-patch"]
    }),
    pat({
      id: "measuring-scale-in-frame",
      displayName: "Measuring scale in the frame",
      modality: "none",
      category: "frame-artifact",
      definition: "A ruler or scale is visible in the photograph. It is not a skin finding, and it is not a measurement you may invent.",
      lookFor: "Notice the scale. Do not read a millimeter number unless the case already records that number.",
      morphologyClues: ["A scale or ruler in the frame"],
      commonContexts: ["Teaching photographs that include a scale"],
      malignantAssociations: [],
      benignAssociations: [],
      mimics: [],
      traps: ["Reading the scale as a thickness or as a diagnosis."],
      doesNotProve: ["It does not prove a size.", "It does not prove a diagnosis."],
      usualRole: "nonspecific",
      sourceIds: ["docutis-case-constraint-2026"],
      supports: "The linked case already says a scale in the frame is not a measurement and not a diagnosis.",
      limitsOfClaim: "This is not a skin pattern. No size was read from the scale.",
      relatedPatternIds: ["printed-circle-and-scale"]
    }),
    pat({
      id: "marker-ink",
      displayName: "Marker ink",
      modality: "none",
      category: "frame-artifact",
      definition: "Ink drawn around a lesion is in the file. It is not the clinical border of the skin lesion.",
      lookFor: "Separate ink from skin before you trace an edge.",
      morphologyClues: ["A drawn line that is not skin"],
      commonContexts: ["Clinical photographs marked before photography"],
      malignantAssociations: [],
      benignAssociations: [],
      mimics: [],
      traps: ["Tracing ink as the border of the lesion."],
      doesNotProve: ["It does not prove an edge.", "It does not prove a diagnosis."],
      usualRole: "nonspecific",
      sourceIds: ["docutis-case-constraint-2026"],
      supports: "The linked case already says ink is not a clinical border.",
      limitsOfClaim: "No skin structure is described by the ink.",
      relatedPatternIds: []
    }),
    pat({
      id: "printed-pointer",
      displayName: "Printed pointer",
      modality: "none",
      category: "frame-artifact",
      definition: "An arrow or other pointer is already in the file. It points at something. It is not a skin finding.",
      lookFor: "Notice the pointer. Do not describe it as skin.",
      morphologyClues: ["A printed arrow"],
      commonContexts: ["Public-domain teaching files that already contain an arrow"],
      malignantAssociations: [],
      benignAssociations: [],
      mimics: [],
      traps: ["Reading the arrow as a structure."],
      doesNotProve: ["It does not prove what it points at.", "It does not prove a diagnosis."],
      usualRole: "nonspecific",
      sourceIds: ["docutis-case-constraint-2026"],
      supports: "The linked case already says the arrow is a pointer, not a skin finding.",
      limitsOfClaim: "The arrow was not added by Docutis.",
      relatedPatternIds: []
    }),
    pat({
      id: "printed-circle-and-scale",
      displayName: "Printed circle and scale",
      modality: "none",
      category: "frame-artifact",
      definition: "A circle and a scale printed on a teaching image. They are not shiny lines and not vessels.",
      lookFor: "Separate the print from the skin and from the vessels.",
      morphologyClues: ["A printed circle", "A printed scale"],
      commonContexts: ["Dermoscopic teaching files with overlay marks"],
      malignantAssociations: [],
      benignAssociations: [],
      mimics: [],
      traps: ["Calling the print a shiny line or a vessel."],
      doesNotProve: ["It does not prove a structure.", "It does not prove a diagnosis."],
      usualRole: "nonspecific",
      sourceIds: ["docutis-case-constraint-2026"],
      supports: "The linked case already says the circle and the scale are printed and are not shiny lines.",
      limitsOfClaim: "No dermoscopic structure is renamed from the print.",
      relatedPatternIds: ["measuring-scale-in-frame", "polymorphous-vessels"]
    })
  ];

  window.DOCUTIS_PATTERNS = Object.freeze({
    schemaVersion: 1,
    reviewStatus: "clinician review required",
    clinicalReview: null,
    disclaimer: "Pattern text is educational and review required. It is not clinician reviewed, not a diagnosis, and not a probability. Case certainty and case weight stay on the case. Linked cases are derived from structured ids, not from the diagnosis alone.",
    sources: sources,
    patterns: Object.freeze(patterns),
    links: Object.freeze([
      Object.freeze({ casePatternId: "pat-g18-01", canonicalId: "asymmetric-thickness" }),
      Object.freeze({ casePatternId: "pat-g18-01-scale", canonicalId: "measuring-scale-in-frame" }),
      Object.freeze({ casePatternId: "pat-g18-02", canonicalId: "notched-border" }),
      Object.freeze({ casePatternId: "pat-g18-02-color", canonicalId: "color-variegation" }),
      Object.freeze({ casePatternId: "pat-g18-03", canonicalId: "color-variegation" }),
      Object.freeze({ casePatternId: "pat-g18-04", canonicalId: "broad-brown-patch" }),
      Object.freeze({ casePatternId: "pat-g18-04-edge", canonicalId: "peripheral-dark-focus" }),
      Object.freeze({ casePatternId: "pat-g18-05", canonicalId: "pale-center" }),
      Object.freeze({ casePatternId: "pat-g18-06", canonicalId: "nodule-beside-pigmented-macule" }),
      Object.freeze({ casePatternId: "pat-g18-06-ink", canonicalId: "marker-ink" }),
      Object.freeze({ casePatternId: "pat-g18-07", canonicalId: "flat-area-with-raised-focus" }),
      Object.freeze({ casePatternId: "pat-g18-07-arrow", canonicalId: "printed-pointer" }),
      Object.freeze({ casePatternId: "pat-g18-08", canonicalId: "solitary-dark-papule" }),
      Object.freeze({ casePatternId: "pat-g18-08-prior", canonicalId: "change-outside-one-frame" }),
      Object.freeze({ casePatternId: "pat-g18-09", canonicalId: "irregular-brown-patch" }),
      Object.freeze({ casePatternId: "pat-g18-09-change", canonicalId: "change-outside-one-frame" }),
      Object.freeze({ casePatternId: "pat-g18-10", canonicalId: "pink-nodule-without-pigment" }),
      Object.freeze({ casePatternId: "pat-g18-11", canonicalId: "polymorphous-vessels" }),
      Object.freeze({ casePatternId: "pat-g18-11-print", canonicalId: "printed-circle-and-scale" }),
      Object.freeze({ casePatternId: "pat-g18-12", canonicalId: "nail-plate-destruction" }),
      Object.freeze({ casePatternId: "pat-g18-12-streak", canonicalId: "pigmented-nail-streak" }),
      Object.freeze({ casePatternId: "pat-g18-13", canonicalId: "pink-scaly-spot" }),
      Object.freeze({ casePatternId: "pat-g18-14", canonicalId: "small-erosion" }),
      Object.freeze({ casePatternId: "pat-g18-15", canonicalId: "shiny-red-papule" }),
      Object.freeze({ casePatternId: "pat-g18-15-vessels", canonicalId: "surface-vessels" }),
      Object.freeze({ casePatternId: "pat-g18-16", canonicalId: "crateriform-center" }),
      Object.freeze({ casePatternId: "pat-g18-16-vessels", canonicalId: "surface-vessels" })
    ]),
    dermoscopicTokenLinks: Object.freeze({
      arborizing_vessels: "arborizing-vessels",
      telangiectasia: "telangiectasia",
      maple_leaf_areas: "maple-leaf-like-areas",
      blue_gray_ovoid_nests: "blue-gray-ovoid-nests",
      polymorphous_vessels: "polymorphous-vessels"
    }),
    unlinkedObservations: Object.freeze([
      Object.freeze({
        casePatternId: "pat-g18-05-name",
        reason: "The case records that the source gives the pale center no histologic name. That absence is not a reusable visual pattern."
      })
    ])
  });
})();
