/* Generated by scripts/review-governance.js. Do not edit by hand. */
window.DOCUTIS_REVIEW_STATUS = Object.freeze({
  "schemaVersion": 1,
  "generatedFrom": "review-data.js",
  "attestationVersion": "docutis-human-clinical-review-v1",
  "latestValidHumanReviewDate": "2026-09-23",
  "reviewers": [
    {
      "id": "reviewer-mna-001",
      "displayName": "Murat Nasuh Aras",
      "professionalRole": "Physician in dermatology specialty training",
      "specialtyOrField": "Dermatology and Venereology — physician in specialty training",
      "trainingStatus": "physician in specialty training",
      "publicDisplayConsent": true
    }
  ],
  "decisions": [
    {
      "id": "decision-ak-2026-09-23-001",
      "assetId": "actinic-keratosis",
      "assetType": "disease",
      "contentFingerprint": "sha256-v1:92302d680f4c645cc1a91c9a827a3e44b0d965fa21fa019144458bd81c27a1dd",
      "schemaVersion": 1,
      "reviewerId": "reviewer-mna-001",
      "reviewerRole": "Physician in dermatology specialty training",
      "reviewDate": "2026-09-23",
      "reviewedSections": [
        "overview",
        "clinical-presentation",
        "diagnostics",
        "dermoscopy",
        "differential-diagnosis",
        "treatment",
        "follow-up",
        "coding",
        "references",
        "histopathology",
        "red-flags",
        "referral",
        "patient-safety"
      ],
      "evidenceSourcesChecked": [
        "https://dermnetnz.org/topics/actinic-keratosis",
        "https://icd.who.int/browse10/2019/en",
        "https://klassifikationen.bfarm.de/icd-10-gm/kode-suche/htmlgm2026/block-l55-l59.htm",
        "https://onlinelibrary.wiley.com/doi/10.1111/ddg.15231",
        "https://register.awmf.org/assets/guidelines/032-022OLl_S3_Aktinische_Keratosen-Plattenepithelkarzinom-PEK_2023-01.pdf",
        "https://register.awmf.org/assets/guidelines/032-052OLl_S3_Praevention-Hautkrebs_2021-09.pdf",
        "https://www.dguv.de/bk-info/icd-10-kapitel/kapitel_12/bk5103/index.jsp",
        "https://www.ema.europa.eu/en/medicines/human/EPAR/aldara",
        "https://www.ema.europa.eu/en/medicines/human/EPAR/zyclara",
        "https://www.fachinfo.de/fi/detail/003786/efudix-r-5-creme",
        "https://www.fachinfo.de/fi/detail/23428/Klisyri-10-mg-g-Salbe",
        "https://www.fachinfo.de/fi/pdf/007858/solaraze-3-gel",
        "https://www.fachinfo.de/fi/pdf/013084/actikerall-5-mg-g-100-mg-g-loesung-zur-anwendung-auf-der-haut",
        "https://www.fachinfo.de/fi/pdf/022967/tolak-r-40-mg-g-creme"
      ],
      "verdict": "approved",
      "requiredCorrections": [],
      "reviewerNotes": "Section-by-section physician review completed. Requested clinical, terminology and source-provenance corrections were applied and verified before final approval.",
      "attestationVersion": "docutis-human-clinical-review-v1",
      "attestationText": "I confirm that I am a human reviewer and that I assessed only the content versions and sections identified by the recorded fingerprints. My decisions apply only to the recorded scope. Clinically meaningful future changes may invalidate the decisions. This educational governance review does not make Docutis an individual diagnostic or treatment service and does not guarantee completeness or universal applicability.",
      "provenance": "human-submitted",
      "supersededBy": null
    },
    {
      "id": "decision-bcc-2026-09-23-001",
      "assetId": "basal-cell-carcinoma",
      "assetType": "disease",
      "contentFingerprint": "sha256-v1:fbc2b272331822060c656dd0680da07e9131ecd3f59f071a71273748f14ad65f",
      "schemaVersion": 1,
      "reviewerId": "reviewer-mna-001",
      "reviewerRole": "Physician in dermatology specialty training",
      "reviewDate": "2026-09-23",
      "reviewedSections": [
        "overview",
        "clinical-presentation",
        "diagnostics",
        "dermoscopy",
        "differential-diagnosis",
        "treatment",
        "follow-up",
        "coding",
        "references",
        "histopathology",
        "red-flags",
        "referral",
        "patient-safety",
        "oncology"
      ],
      "evidenceSourcesChecked": [
        "https://dermnetnz.org/topics/basal-cell-carcinoma",
        "https://icd.who.int/browse10/2019/en",
        "https://klassifikationen.bfarm.de/icd-10-gm/kode-suche/htmlgm2026/block-c43-c44.htm",
        "https://register.awmf.org/assets/guidelines/032-021l_S2k_Basalzellkarzinom-der-Haut_2024-07.pdf",
        "https://whobluebooks.iarc.who.int/structures/skintumours/",
        "https://www.aad.org/member/clinical-quality/guidelines/bcc",
        "https://www.dguv.de/bk-info/icd-10-kapitel/kapitel_12/bk5103/index.jsp",
        "https://www.ema.europa.eu/en/medicines/human/EPAR/ameluz",
        "https://www.ema.europa.eu/en/medicines/human/EPAR/erivedge",
        "https://www.ema.europa.eu/en/medicines/human/EPAR/libtayo",
        "https://www.ema.europa.eu/en/medicines/human/EPAR/odomzo",
        "https://www.fachinfo.de/fi/detail/003786/efudix-r-5-creme",
        "https://www.fachinfo.de/fi/detail/007185/metvix-r-160-mg-g-creme",
        "https://www.fachinfo.de/fi/pdf/003976",
        "https://www.who.int/standards/classifications/other-classifications/international-classification-of-diseases-for-oncology"
      ],
      "verdict": "approved",
      "requiredCorrections": [],
      "reviewerNotes": "Physician attestation for basal-cell-carcinoma disease asset at the recorded fingerprint only. S2k Table 2 exact 6/10/20 mm equality remains unresolved; do not invent ≥/≤ wording. Ameluz/Metvix/AAD metadata-quality items do not alter approved clinical recommendations. Related BCC assets (basal-cell-carcinoma-de, quiz, visual) remain independent unreviewed units. This decision does not apply to actinic-keratosis or any other disease.",
      "attestationVersion": "docutis-human-clinical-review-v1",
      "attestationText": "I confirm that I am a human reviewer and that I assessed only the content versions and sections identified by the recorded fingerprints. My decisions apply only to the recorded scope. Clinically meaningful future changes may invalidate the decisions. This educational governance review does not make Docutis an individual diagnostic or treatment service and does not guarantee completeness or universal applicability.",
      "provenance": "human-submitted",
      "supersededBy": null
    }
  ],
  "assets": [
    {
      "id": "actinic-keratosis",
      "assetType": "disease",
      "title": "Actinic Keratosis",
      "schemaVersion": 1,
      "currentFingerprint": "sha256-v1:92302d680f4c645cc1a91c9a827a3e44b0d965fa21fa019144458bd81c27a1dd",
      "sections": [
        "overview",
        "clinical-presentation",
        "diagnostics",
        "dermoscopy",
        "differential-diagnosis",
        "treatment",
        "follow-up",
        "coding",
        "references",
        "histopathology",
        "red-flags",
        "referral",
        "patient-safety"
      ],
      "evidenceSources": [
        "https://dermnetnz.org/topics/actinic-keratosis",
        "https://icd.who.int/browse10/2019/en",
        "https://klassifikationen.bfarm.de/icd-10-gm/kode-suche/htmlgm2026/block-l55-l59.htm",
        "https://onlinelibrary.wiley.com/doi/10.1111/ddg.15231",
        "https://register.awmf.org/assets/guidelines/032-022OLl_S3_Aktinische_Keratosen-Plattenepithelkarzinom-PEK_2023-01.pdf",
        "https://register.awmf.org/assets/guidelines/032-052OLl_S3_Praevention-Hautkrebs_2021-09.pdf",
        "https://www.dguv.de/bk-info/icd-10-kapitel/kapitel_12/bk5103/index.jsp",
        "https://www.ema.europa.eu/en/medicines/human/EPAR/aldara",
        "https://www.ema.europa.eu/en/medicines/human/EPAR/zyclara",
        "https://www.fachinfo.de/fi/detail/003786/efudix-r-5-creme",
        "https://www.fachinfo.de/fi/detail/23428/Klisyri-10-mg-g-Salbe",
        "https://www.fachinfo.de/fi/pdf/007858/solaraze-3-gel",
        "https://www.fachinfo.de/fi/pdf/013084/actikerall-5-mg-g-100-mg-g-loesung-zur-anwendung-auf-der-haut",
        "https://www.fachinfo.de/fi/pdf/022967/tolak-r-40-mg-g-creme"
      ],
      "evidenceMetadata": [
        {
          "title": "Actinic keratosis",
          "organization": "DermNet",
          "type": "clinical reference",
          "year": null,
          "version": null,
          "doi": null,
          "url": "https://dermnetnz.org/topics/actinic-keratosis",
          "metadataCheckedAt": "2026-09-20"
        },
        {
          "title": "ICD-10 Version: 2019",
          "organization": "World Health Organization",
          "type": "official classification",
          "year": null,
          "version": "2019",
          "doi": null,
          "url": "https://icd.who.int/browse10/2019/en",
          "metadataCheckedAt": "2026-09-15"
        },
        {
          "title": "ICD-10-GM Version 2026 — L57.0 Aktinische Keratose",
          "organization": "BfArM",
          "type": "official classification",
          "year": 2026,
          "version": "2026",
          "doi": null,
          "url": "https://klassifikationen.bfarm.de/icd-10-gm/kode-suche/htmlgm2026/block-l55-l59.htm",
          "metadataCheckedAt": "2026-09-20"
        },
        {
          "title": "S3 guideline: actinic keratosis and cutaneous squamous cell carcinoma — update 2023, part 1: treatment of actinic keratosis, actinic cheilitis, Bowen disease, occupational disease and structures of care",
          "organization": "German Dermatological Society guideline group / AWMF 032/022OL",
          "type": "guideline",
          "year": 2023,
          "version": "2.0",
          "doi": "10.1111/ddg.15231",
          "url": "https://onlinelibrary.wiley.com/doi/10.1111/ddg.15231",
          "metadataCheckedAt": "2026-09-20"
        },
        {
          "title": "S3-Leitlinie Aktinische Keratose und Plattenepithelkarzinom der Haut (Langfassung)",
          "organization": "Leitlinienprogramm Onkologie / AWMF",
          "type": "guideline",
          "year": 2023,
          "version": "2.0; AWMF 032/022OL",
          "doi": null,
          "url": "https://register.awmf.org/assets/guidelines/032-022OLl_S3_Aktinische_Keratosen-Plattenepithelkarzinom-PEK_2023-01.pdf",
          "metadataCheckedAt": "2026-09-20"
        },
        {
          "title": "S3-Leitlinie Prävention von Hautkrebs",
          "organization": "Leitlinienprogramm Onkologie / AWMF",
          "type": "guideline",
          "year": 2021,
          "version": "2.1; AWMF 032/052OL",
          "doi": null,
          "url": "https://register.awmf.org/assets/guidelines/032-052OLl_S3_Praevention-Hautkrebs_2021-09.pdf",
          "metadataCheckedAt": "2026-09-23"
        },
        {
          "title": "BK 5103 — Squamous cell carcinomas or multiple actinic keratoses of the skin caused by natural UV radiation",
          "organization": "DGUV",
          "type": "clinical reference",
          "year": null,
          "version": null,
          "doi": null,
          "url": "https://www.dguv.de/bk-info/icd-10-kapitel/kapitel_12/bk5103/index.jsp",
          "metadataCheckedAt": "2026-09-20"
        },
        {
          "title": "Aldara 5% cream — EPAR Product Information",
          "organization": "European Medicines Agency",
          "type": "clinical reference",
          "year": null,
          "version": null,
          "doi": null,
          "url": "https://www.ema.europa.eu/en/medicines/human/EPAR/aldara",
          "metadataCheckedAt": "2026-09-20"
        },
        {
          "title": "Zyclara 3.75% cream — EPAR Product Information",
          "organization": "European Medicines Agency",
          "type": "clinical reference",
          "year": null,
          "version": null,
          "doi": null,
          "url": "https://www.ema.europa.eu/en/medicines/human/EPAR/zyclara",
          "metadataCheckedAt": "2026-09-20"
        },
        {
          "title": "Efudix 5% cream — German Fachinformation",
          "organization": "German product information",
          "type": "clinical reference",
          "year": null,
          "version": null,
          "doi": null,
          "url": "https://www.fachinfo.de/fi/detail/003786/efudix-r-5-creme",
          "metadataCheckedAt": "2026-09-20"
        },
        {
          "title": "Klisyri 10 mg/g ointment (tirbanibulin) — German Fachinformation / EU product information",
          "organization": "German product information / EMA",
          "type": "clinical reference",
          "year": null,
          "version": null,
          "doi": null,
          "url": "https://www.fachinfo.de/fi/detail/23428/Klisyri-10-mg-g-Salbe",
          "metadataCheckedAt": "2026-09-20"
        },
        {
          "title": "Solaraze 3% gel — German Fachinformation",
          "organization": "German product information",
          "type": "clinical reference",
          "year": null,
          "version": null,
          "doi": null,
          "url": "https://www.fachinfo.de/fi/pdf/007858/solaraze-3-gel",
          "metadataCheckedAt": "2026-09-20"
        },
        {
          "title": "Actikerall 5 mg/g + 100 mg/g Lösung zur Anwendung auf der Haut — Fachinformation",
          "organization": "Fachinfo-Service / Almirall Hermal GmbH / German product information",
          "type": "clinical reference",
          "year": null,
          "version": "January 2023",
          "doi": null,
          "url": "https://www.fachinfo.de/fi/pdf/013084/actikerall-5-mg-g-100-mg-g-loesung-zur-anwendung-auf-der-haut",
          "metadataCheckedAt": "2026-09-23"
        },
        {
          "title": "Tolak 40 mg/g Creme — Fachinformation",
          "organization": "Fachinfo-Service / German product information",
          "type": "clinical reference",
          "year": null,
          "version": null,
          "doi": null,
          "url": "https://www.fachinfo.de/fi/pdf/022967/tolak-r-40-mg-g-creme",
          "metadataCheckedAt": "2026-09-23"
        }
      ],
      "status": "clinician reviewed",
      "activeDecisionId": "decision-ak-2026-09-23-001",
      "history": [
        {
          "id": "decision-ak-2026-09-23-001",
          "assetId": "actinic-keratosis",
          "assetType": "disease",
          "contentFingerprint": "sha256-v1:92302d680f4c645cc1a91c9a827a3e44b0d965fa21fa019144458bd81c27a1dd",
          "schemaVersion": 1,
          "reviewerId": "reviewer-mna-001",
          "reviewerRole": "Physician in dermatology specialty training",
          "reviewDate": "2026-09-23",
          "reviewedSections": [
            "overview",
            "clinical-presentation",
            "diagnostics",
            "dermoscopy",
            "differential-diagnosis",
            "treatment",
            "follow-up",
            "coding",
            "references",
            "histopathology",
            "red-flags",
            "referral",
            "patient-safety"
          ],
          "evidenceSourcesChecked": [
            "https://dermnetnz.org/topics/actinic-keratosis",
            "https://icd.who.int/browse10/2019/en",
            "https://klassifikationen.bfarm.de/icd-10-gm/kode-suche/htmlgm2026/block-l55-l59.htm",
            "https://onlinelibrary.wiley.com/doi/10.1111/ddg.15231",
            "https://register.awmf.org/assets/guidelines/032-022OLl_S3_Aktinische_Keratosen-Plattenepithelkarzinom-PEK_2023-01.pdf",
            "https://register.awmf.org/assets/guidelines/032-052OLl_S3_Praevention-Hautkrebs_2021-09.pdf",
            "https://www.dguv.de/bk-info/icd-10-kapitel/kapitel_12/bk5103/index.jsp",
            "https://www.ema.europa.eu/en/medicines/human/EPAR/aldara",
            "https://www.ema.europa.eu/en/medicines/human/EPAR/zyclara",
            "https://www.fachinfo.de/fi/detail/003786/efudix-r-5-creme",
            "https://www.fachinfo.de/fi/detail/23428/Klisyri-10-mg-g-Salbe",
            "https://www.fachinfo.de/fi/pdf/007858/solaraze-3-gel",
            "https://www.fachinfo.de/fi/pdf/013084/actikerall-5-mg-g-100-mg-g-loesung-zur-anwendung-auf-der-haut",
            "https://www.fachinfo.de/fi/pdf/022967/tolak-r-40-mg-g-creme"
          ],
          "verdict": "approved",
          "requiredCorrections": [],
          "reviewerNotes": "Section-by-section physician review completed. Requested clinical, terminology and source-provenance corrections were applied and verified before final approval.",
          "attestationVersion": "docutis-human-clinical-review-v1",
          "attestationText": "I confirm that I am a human reviewer and that I assessed only the content versions and sections identified by the recorded fingerprints. My decisions apply only to the recorded scope. Clinically meaningful future changes may invalidate the decisions. This educational governance review does not make Docutis an individual diagnostic or treatment service and does not guarantee completeness or universal applicability.",
          "provenance": "human-submitted",
          "supersededBy": null
        }
      ],
      "awaitingSections": []
    },
    {
      "id": "basal-cell-carcinoma",
      "assetType": "disease",
      "title": "Basal Cell Carcinoma",
      "schemaVersion": 1,
      "currentFingerprint": "sha256-v1:fbc2b272331822060c656dd0680da07e9131ecd3f59f071a71273748f14ad65f",
      "sections": [
        "overview",
        "clinical-presentation",
        "diagnostics",
        "dermoscopy",
        "differential-diagnosis",
        "treatment",
        "follow-up",
        "coding",
        "references",
        "histopathology",
        "red-flags",
        "referral",
        "patient-safety",
        "oncology"
      ],
      "evidenceSources": [
        "https://dermnetnz.org/topics/basal-cell-carcinoma",
        "https://icd.who.int/browse10/2019/en",
        "https://klassifikationen.bfarm.de/icd-10-gm/kode-suche/htmlgm2026/block-c43-c44.htm",
        "https://register.awmf.org/assets/guidelines/032-021l_S2k_Basalzellkarzinom-der-Haut_2024-07.pdf",
        "https://whobluebooks.iarc.who.int/structures/skintumours/",
        "https://www.aad.org/member/clinical-quality/guidelines/bcc",
        "https://www.dguv.de/bk-info/icd-10-kapitel/kapitel_12/bk5103/index.jsp",
        "https://www.ema.europa.eu/en/medicines/human/EPAR/ameluz",
        "https://www.ema.europa.eu/en/medicines/human/EPAR/erivedge",
        "https://www.ema.europa.eu/en/medicines/human/EPAR/libtayo",
        "https://www.ema.europa.eu/en/medicines/human/EPAR/odomzo",
        "https://www.fachinfo.de/fi/detail/003786/efudix-r-5-creme",
        "https://www.fachinfo.de/fi/detail/007185/metvix-r-160-mg-g-creme",
        "https://www.fachinfo.de/fi/pdf/003976",
        "https://www.who.int/standards/classifications/other-classifications/international-classification-of-diseases-for-oncology"
      ],
      "evidenceMetadata": [
        {
          "title": "Basal cell carcinoma",
          "organization": "DermNet",
          "type": "clinical reference",
          "year": null,
          "version": null,
          "doi": null,
          "url": "https://dermnetnz.org/topics/basal-cell-carcinoma",
          "metadataCheckedAt": "2026-09-23"
        },
        {
          "title": "ICD-10 Version: 2019",
          "organization": "World Health Organization",
          "type": "official classification",
          "year": null,
          "version": "2019",
          "doi": null,
          "url": "https://icd.who.int/browse10/2019/en",
          "metadataCheckedAt": "2026-09-15"
        },
        {
          "title": "ICD-10-GM Version 2026 — C43–C44 Melanom und sonstige bösartige Neubildungen der Haut",
          "organization": "BfArM",
          "type": "official classification",
          "year": 2026,
          "version": "2026",
          "doi": null,
          "url": "https://klassifikationen.bfarm.de/icd-10-gm/kode-suche/htmlgm2026/block-c43-c44.htm",
          "metadataCheckedAt": "2026-09-23"
        },
        {
          "title": "S2k-Leitlinie Basalzellkarzinom der Haut",
          "organization": "German Dermatological Society guideline group / AWMF 032-021",
          "type": "guideline",
          "year": 2024,
          "version": "9.0; AWMF 032-021",
          "doi": null,
          "url": "https://register.awmf.org/assets/guidelines/032-021l_S2k_Basalzellkarzinom-der-Haut_2024-07.pdf",
          "metadataCheckedAt": "2026-09-23"
        },
        {
          "title": "WHO Classification of Skin Tumours, fifth edition",
          "organization": "WHO Classification of Tumours Editorial Board / IARC",
          "type": "official classification",
          "year": 2025,
          "version": "5th edition",
          "doi": null,
          "url": "https://whobluebooks.iarc.who.int/structures/skintumours/",
          "metadataCheckedAt": "2026-09-15"
        },
        {
          "title": "Basal cell carcinoma clinical guideline",
          "organization": "American Academy of Dermatology",
          "type": "guideline",
          "year": null,
          "version": null,
          "doi": null,
          "url": "https://www.aad.org/member/clinical-quality/guidelines/bcc",
          "metadataCheckedAt": "2026-09-20"
        },
        {
          "title": "BK 5103 — Squamous cell carcinomas or multiple actinic keratoses of the skin caused by natural UV radiation",
          "organization": "DGUV",
          "type": "clinical reference",
          "year": null,
          "version": null,
          "doi": null,
          "url": "https://www.dguv.de/bk-info/icd-10-kapitel/kapitel_12/bk5103/index.jsp",
          "metadataCheckedAt": "2026-09-20"
        },
        {
          "title": "Ameluz — EPAR Product Information",
          "organization": "European Medicines Agency",
          "type": "clinical reference",
          "year": null,
          "version": null,
          "doi": null,
          "url": "https://www.ema.europa.eu/en/medicines/human/EPAR/ameluz",
          "metadataCheckedAt": "2026-09-23"
        },
        {
          "title": "Erivedge (vismodegib) — EPAR Product Information",
          "organization": "European Medicines Agency",
          "type": "clinical reference",
          "year": null,
          "version": null,
          "doi": null,
          "url": "https://www.ema.europa.eu/en/medicines/human/EPAR/erivedge",
          "metadataCheckedAt": "2026-09-23"
        },
        {
          "title": "Libtayo (cemiplimab) — EPAR Product Information",
          "organization": "European Medicines Agency",
          "type": "clinical reference",
          "year": null,
          "version": null,
          "doi": null,
          "url": "https://www.ema.europa.eu/en/medicines/human/EPAR/libtayo",
          "metadataCheckedAt": "2026-09-23"
        },
        {
          "title": "Odomzo (sonidegib) — EPAR Product Information",
          "organization": "European Medicines Agency",
          "type": "clinical reference",
          "year": null,
          "version": null,
          "doi": null,
          "url": "https://www.ema.europa.eu/en/medicines/human/EPAR/odomzo",
          "metadataCheckedAt": "2026-09-23"
        },
        {
          "title": "Efudix 5% cream — German Fachinformation",
          "organization": "German product information",
          "type": "clinical reference",
          "year": null,
          "version": null,
          "doi": null,
          "url": "https://www.fachinfo.de/fi/detail/003786/efudix-r-5-creme",
          "metadataCheckedAt": "2026-09-20"
        },
        {
          "title": "Metvix 160 mg/g Creme — German Fachinformation",
          "organization": "Fachinfo-Service / German product information",
          "type": "clinical reference",
          "year": null,
          "version": "12/2024",
          "doi": null,
          "url": "https://www.fachinfo.de/fi/detail/007185/metvix-r-160-mg-g-creme",
          "metadataCheckedAt": "2026-09-23"
        },
        {
          "title": "Aldara 5% Creme — German Fachinformation",
          "organization": "Fachinfo-Service / German product information",
          "type": "clinical reference",
          "year": null,
          "version": "Februar 2024",
          "doi": null,
          "url": "https://www.fachinfo.de/fi/pdf/003976",
          "metadataCheckedAt": "2026-09-23"
        },
        {
          "title": "International Classification of Diseases for Oncology, Third Edition, Second Revision",
          "organization": "World Health Organization / International Agency for Research on Cancer",
          "type": "official classification",
          "year": 2019,
          "version": "ICD-O-3.2",
          "doi": null,
          "url": "https://www.who.int/standards/classifications/other-classifications/international-classification-of-diseases-for-oncology",
          "metadataCheckedAt": "2026-09-15"
        }
      ],
      "status": "clinician reviewed",
      "activeDecisionId": "decision-bcc-2026-09-23-001",
      "history": [
        {
          "id": "decision-bcc-2026-09-23-001",
          "assetId": "basal-cell-carcinoma",
          "assetType": "disease",
          "contentFingerprint": "sha256-v1:fbc2b272331822060c656dd0680da07e9131ecd3f59f071a71273748f14ad65f",
          "schemaVersion": 1,
          "reviewerId": "reviewer-mna-001",
          "reviewerRole": "Physician in dermatology specialty training",
          "reviewDate": "2026-09-23",
          "reviewedSections": [
            "overview",
            "clinical-presentation",
            "diagnostics",
            "dermoscopy",
            "differential-diagnosis",
            "treatment",
            "follow-up",
            "coding",
            "references",
            "histopathology",
            "red-flags",
            "referral",
            "patient-safety",
            "oncology"
          ],
          "evidenceSourcesChecked": [
            "https://dermnetnz.org/topics/basal-cell-carcinoma",
            "https://icd.who.int/browse10/2019/en",
            "https://klassifikationen.bfarm.de/icd-10-gm/kode-suche/htmlgm2026/block-c43-c44.htm",
            "https://register.awmf.org/assets/guidelines/032-021l_S2k_Basalzellkarzinom-der-Haut_2024-07.pdf",
            "https://whobluebooks.iarc.who.int/structures/skintumours/",
            "https://www.aad.org/member/clinical-quality/guidelines/bcc",
            "https://www.dguv.de/bk-info/icd-10-kapitel/kapitel_12/bk5103/index.jsp",
            "https://www.ema.europa.eu/en/medicines/human/EPAR/ameluz",
            "https://www.ema.europa.eu/en/medicines/human/EPAR/erivedge",
            "https://www.ema.europa.eu/en/medicines/human/EPAR/libtayo",
            "https://www.ema.europa.eu/en/medicines/human/EPAR/odomzo",
            "https://www.fachinfo.de/fi/detail/003786/efudix-r-5-creme",
            "https://www.fachinfo.de/fi/detail/007185/metvix-r-160-mg-g-creme",
            "https://www.fachinfo.de/fi/pdf/003976",
            "https://www.who.int/standards/classifications/other-classifications/international-classification-of-diseases-for-oncology"
          ],
          "verdict": "approved",
          "requiredCorrections": [],
          "reviewerNotes": "Physician attestation for basal-cell-carcinoma disease asset at the recorded fingerprint only. S2k Table 2 exact 6/10/20 mm equality remains unresolved; do not invent ≥/≤ wording. Ameluz/Metvix/AAD metadata-quality items do not alter approved clinical recommendations. Related BCC assets (basal-cell-carcinoma-de, quiz, visual) remain independent unreviewed units. This decision does not apply to actinic-keratosis or any other disease.",
          "attestationVersion": "docutis-human-clinical-review-v1",
          "attestationText": "I confirm that I am a human reviewer and that I assessed only the content versions and sections identified by the recorded fingerprints. My decisions apply only to the recorded scope. Clinically meaningful future changes may invalidate the decisions. This educational governance review does not make Docutis an individual diagnostic or treatment service and does not guarantee completeness or universal applicability.",
          "provenance": "human-submitted",
          "supersededBy": null
        }
      ],
      "awaitingSections": []
    },
    {
      "id": "cutaneous-melanoma",
      "assetType": "disease",
      "title": "Cutaneous Melanoma",
      "schemaVersion": 1,
      "currentFingerprint": "sha256-v1:80d9ddc08809c1c99513adc9972d5bf625331f7b97ff53339303e50c614facbe",
      "sections": [
        "overview",
        "clinical-presentation",
        "diagnostics",
        "dermoscopy",
        "differential-diagnosis",
        "treatment",
        "follow-up",
        "coding",
        "references",
        "histopathology",
        "red-flags",
        "referral",
        "oncology"
      ],
      "evidenceSources": [
        "https://pubmed.ncbi.nlm.nih.gov/39700658/",
        "https://pubmed.ncbi.nlm.nih.gov/39709737/",
        "https://www.cancer.gov/types/skin/hp/melanoma-treatment-pdq"
      ],
      "evidenceMetadata": [
        {
          "title": "European consensus-based interdisciplinary guideline for melanoma. Part 1: Diagnostics — Update 2024",
          "organization": "EADO / EDF / EORTC",
          "type": "guideline",
          "year": 2025,
          "version": "2024 update; part 1",
          "doi": "10.1016/j.ejca.2024.115152",
          "url": "https://pubmed.ncbi.nlm.nih.gov/39700658/",
          "metadataCheckedAt": "2026-09-20"
        },
        {
          "title": "European consensus-based interdisciplinary guideline for melanoma. Part 2: Treatment — Update 2024",
          "organization": "EADO / EDF / EORTC",
          "type": "guideline",
          "year": 2025,
          "version": "2024 update; part 2",
          "doi": "10.1016/j.ejca.2024.115153",
          "url": "https://pubmed.ncbi.nlm.nih.gov/39709737/",
          "metadataCheckedAt": "2026-09-20"
        },
        {
          "title": "Melanoma Treatment (PDQ®) — Health Professional Version",
          "organization": "National Cancer Institute",
          "type": "clinical reference",
          "year": null,
          "version": null,
          "doi": null,
          "url": "https://www.cancer.gov/types/skin/hp/melanoma-treatment-pdq",
          "metadataCheckedAt": "2026-09-20"
        }
      ],
      "status": "review required",
      "activeDecisionId": null,
      "history": [],
      "awaitingSections": [
        "overview",
        "clinical-presentation",
        "diagnostics",
        "dermoscopy",
        "differential-diagnosis",
        "treatment",
        "follow-up",
        "coding",
        "references",
        "histopathology",
        "red-flags",
        "referral",
        "oncology"
      ]
    },
    {
      "id": "atopic-dermatitis",
      "assetType": "disease",
      "title": "Atopic Dermatitis",
      "schemaVersion": 1,
      "currentFingerprint": "sha256-v1:f4c9fe56147923b8e0fd25d36dd06851b672707e72721bad398b31c7e48d5f35",
      "sections": [
        "overview",
        "clinical-presentation",
        "diagnostics",
        "dermoscopy",
        "differential-diagnosis",
        "treatment",
        "follow-up",
        "coding",
        "references",
        "red-flags",
        "referral",
        "patient-safety"
      ],
      "evidenceSources": [
        "https://dermnetnz.org/topics/atopic-dermatitis",
        "https://pubmed.ncbi.nlm.nih.gov/36641009/",
        "https://pubmed.ncbi.nlm.nih.gov/37943240/"
      ],
      "evidenceMetadata": [
        {
          "title": "Atopic dermatitis",
          "organization": "DermNet",
          "type": "clinical reference",
          "year": null,
          "version": null,
          "doi": null,
          "url": "https://dermnetnz.org/topics/atopic-dermatitis",
          "metadataCheckedAt": "2026-09-20"
        },
        {
          "title": "Guidelines of care for the management of atopic dermatitis in adults with topical therapies",
          "organization": "American Academy of Dermatology",
          "type": "guideline",
          "year": 2023,
          "version": null,
          "doi": "10.1016/j.jaad.2022.12.029",
          "url": "https://pubmed.ncbi.nlm.nih.gov/36641009/",
          "metadataCheckedAt": "2026-09-20"
        },
        {
          "title": "Guidelines of care for the management of atopic dermatitis in adults with phototherapy and systemic therapies",
          "organization": "American Academy of Dermatology",
          "type": "guideline",
          "year": 2024,
          "version": null,
          "doi": "10.1016/j.jaad.2023.08.102",
          "url": "https://pubmed.ncbi.nlm.nih.gov/37943240/",
          "metadataCheckedAt": "2026-09-20"
        }
      ],
      "status": "review required",
      "activeDecisionId": null,
      "history": [],
      "awaitingSections": [
        "overview",
        "clinical-presentation",
        "diagnostics",
        "dermoscopy",
        "differential-diagnosis",
        "treatment",
        "follow-up",
        "coding",
        "references",
        "red-flags",
        "referral",
        "patient-safety"
      ]
    },
    {
      "id": "plaque-psoriasis",
      "assetType": "disease",
      "title": "Plaque Psoriasis",
      "schemaVersion": 1,
      "currentFingerprint": "sha256-v1:02f24e6fbe331ca09cc4fde5c1357c5163690195636a33d157f03927fcf31339",
      "sections": [
        "overview",
        "clinical-presentation",
        "diagnostics",
        "dermoscopy",
        "differential-diagnosis",
        "treatment",
        "follow-up",
        "coding",
        "references",
        "red-flags",
        "referral"
      ],
      "evidenceSources": [
        "https://dermnetnz.org/topics/psoriasis",
        "https://www.aad.org/member/clinical-quality/guidelines/psoriasis",
        "https://www.guidelines.edf.one/guidelines/psoriasis-guideline"
      ],
      "evidenceMetadata": [
        {
          "title": "Psoriasis",
          "organization": "DermNet",
          "type": "clinical reference",
          "year": null,
          "version": null,
          "doi": null,
          "url": "https://dermnetnz.org/topics/psoriasis",
          "metadataCheckedAt": "2026-09-20"
        },
        {
          "title": "Psoriasis clinical guideline",
          "organization": "American Academy of Dermatology",
          "type": "guideline",
          "year": null,
          "version": null,
          "doi": null,
          "url": "https://www.aad.org/member/clinical-quality/guidelines/psoriasis",
          "metadataCheckedAt": "2026-09-17"
        },
        {
          "title": "Living EuroGuiDerm Guideline for the systemic treatment of psoriasis vulgaris",
          "organization": "European Dermatology Forum / EuroGuiDerm",
          "type": "guideline",
          "year": null,
          "version": "September 2023; partial update February 2025",
          "doi": null,
          "url": "https://www.guidelines.edf.one/guidelines/psoriasis-guideline",
          "metadataCheckedAt": "2026-09-20"
        }
      ],
      "status": "review required",
      "activeDecisionId": null,
      "history": [],
      "awaitingSections": [
        "overview",
        "clinical-presentation",
        "diagnostics",
        "dermoscopy",
        "differential-diagnosis",
        "treatment",
        "follow-up",
        "coding",
        "references",
        "red-flags",
        "referral"
      ]
    },
    {
      "id": "acne-vulgaris",
      "assetType": "disease",
      "title": "Acne Vulgaris",
      "schemaVersion": 1,
      "currentFingerprint": "sha256-v1:bfd1ea796e0fb171d632d7f88d916691703ef8883595cf7350dd8a0984c39a30",
      "sections": [
        "overview",
        "clinical-presentation",
        "diagnostics",
        "dermoscopy",
        "differential-diagnosis",
        "treatment",
        "follow-up",
        "coding",
        "references",
        "red-flags",
        "referral"
      ],
      "evidenceSources": [
        "https://dermnetnz.org/topics/acne-vulgaris",
        "https://pubmed.ncbi.nlm.nih.gov/38300170/"
      ],
      "evidenceMetadata": [
        {
          "title": "Acne vulgaris",
          "organization": "DermNet",
          "type": "clinical reference",
          "year": null,
          "version": null,
          "doi": null,
          "url": "https://dermnetnz.org/topics/acne-vulgaris",
          "metadataCheckedAt": "2026-09-20"
        },
        {
          "title": "Guidelines of care for the management of acne vulgaris",
          "organization": "American Academy of Dermatology",
          "type": "guideline",
          "year": 2024,
          "version": null,
          "doi": "10.1016/j.jaad.2023.12.017",
          "url": "https://pubmed.ncbi.nlm.nih.gov/38300170/",
          "metadataCheckedAt": "2026-09-20"
        }
      ],
      "status": "review required",
      "activeDecisionId": null,
      "history": [],
      "awaitingSections": [
        "overview",
        "clinical-presentation",
        "diagnostics",
        "dermoscopy",
        "differential-diagnosis",
        "treatment",
        "follow-up",
        "coding",
        "references",
        "red-flags",
        "referral"
      ]
    },
    {
      "id": "rosacea",
      "assetType": "disease",
      "title": "Rosacea",
      "schemaVersion": 1,
      "currentFingerprint": "sha256-v1:f3dc5cd051aa95294ebe867e10182d2fad6e3ab438f78a61279a597187ba5612",
      "sections": [
        "overview",
        "clinical-presentation",
        "diagnostics",
        "dermoscopy",
        "differential-diagnosis",
        "treatment",
        "follow-up",
        "coding",
        "references",
        "red-flags",
        "referral",
        "patient-safety"
      ],
      "evidenceSources": [
        "https://dermnetnz.org/topics/rosacea",
        "https://pubmed.ncbi.nlm.nih.gov/35929658/"
      ],
      "evidenceMetadata": [
        {
          "title": "Rosacea",
          "organization": "DermNet",
          "type": "clinical reference",
          "year": null,
          "version": null,
          "doi": null,
          "url": "https://dermnetnz.org/topics/rosacea",
          "metadataCheckedAt": "2026-09-20"
        },
        {
          "title": "S2k guideline: Rosacea",
          "organization": "German Dermatological Society guideline group",
          "type": "guideline",
          "year": 2022,
          "version": null,
          "doi": "10.1111/ddg.14849",
          "url": "https://pubmed.ncbi.nlm.nih.gov/35929658/",
          "metadataCheckedAt": "2026-09-20"
        }
      ],
      "status": "review required",
      "activeDecisionId": null,
      "history": [],
      "awaitingSections": [
        "overview",
        "clinical-presentation",
        "diagnostics",
        "dermoscopy",
        "differential-diagnosis",
        "treatment",
        "follow-up",
        "coding",
        "references",
        "red-flags",
        "referral",
        "patient-safety"
      ]
    },
    {
      "id": "tinea-corporis",
      "assetType": "disease",
      "title": "Tinea Corporis",
      "schemaVersion": 1,
      "currentFingerprint": "sha256-v1:f20cdb28e4bf87cef7eb15e51afdbf6a4767cd283c6764db75ff7d0618fe72e2",
      "sections": [
        "overview",
        "clinical-presentation",
        "diagnostics",
        "dermoscopy",
        "differential-diagnosis",
        "treatment",
        "follow-up",
        "coding",
        "references",
        "red-flags",
        "referral",
        "patient-safety"
      ],
      "evidenceSources": [
        "https://dermnetnz.org/topics/tinea-corporis",
        "https://www.cdc.gov/ringworm/hcp/clinical-overview/"
      ],
      "evidenceMetadata": [
        {
          "title": "Tinea corporis",
          "organization": "DermNet",
          "type": "clinical reference",
          "year": null,
          "version": null,
          "doi": null,
          "url": "https://dermnetnz.org/topics/tinea-corporis",
          "metadataCheckedAt": "2026-09-20"
        },
        {
          "title": "Clinical Overview of Ringworm",
          "organization": "Centers for Disease Control and Prevention",
          "type": "clinical reference",
          "year": 2024,
          "version": null,
          "doi": null,
          "url": "https://www.cdc.gov/ringworm/hcp/clinical-overview/",
          "metadataCheckedAt": "2026-09-20"
        }
      ],
      "status": "review required",
      "activeDecisionId": null,
      "history": [],
      "awaitingSections": [
        "overview",
        "clinical-presentation",
        "diagnostics",
        "dermoscopy",
        "differential-diagnosis",
        "treatment",
        "follow-up",
        "coding",
        "references",
        "red-flags",
        "referral",
        "patient-safety"
      ]
    },
    {
      "id": "melanoma-evolution",
      "assetType": "quiz",
      "title": "Which ABCDE feature explicitly describes change over time?",
      "schemaVersion": 1,
      "currentFingerprint": "sha256-v1:90116bee492bf05294115bb3d557bbf6546b27193f7a27c71d96784fe02c4212",
      "sections": [
        "prompt",
        "options",
        "best-answer",
        "explanation",
        "safety-notice",
        "references"
      ],
      "evidenceSources": [
        "https://pubmed.ncbi.nlm.nih.gov/39700658/"
      ],
      "evidenceMetadata": [
        {
          "title": "European consensus-based interdisciplinary guideline for melanoma. Part 1: Diagnostics — Update 2024",
          "organization": "EADO / EDF / EORTC",
          "type": "guideline",
          "year": 2025,
          "version": "2024 update; part 1",
          "doi": "10.1016/j.ejca.2024.115152",
          "url": "https://pubmed.ncbi.nlm.nih.gov/39700658/",
          "metadataCheckedAt": "2026-09-20"
        }
      ],
      "status": "review required",
      "activeDecisionId": null,
      "history": [],
      "awaitingSections": [
        "prompt",
        "options",
        "best-answer",
        "explanation",
        "safety-notice",
        "references"
      ]
    },
    {
      "id": "bcc-dermoscopy",
      "assetType": "quiz",
      "title": "Which schematic vascular clue is classically associated with basal cell carcinoma?",
      "schemaVersion": 1,
      "currentFingerprint": "sha256-v1:088c6b43b3713d63d8d92ab1b5c9cc1fedd438057e0f5648013e8b098254f3f0",
      "sections": [
        "prompt",
        "options",
        "best-answer",
        "explanation",
        "safety-notice",
        "references"
      ],
      "evidenceSources": [
        "https://dermnetnz.org/topics/basal-cell-carcinoma"
      ],
      "evidenceMetadata": [
        {
          "title": "Basal cell carcinoma",
          "organization": "DermNet",
          "type": "clinical reference",
          "year": null,
          "version": null,
          "doi": null,
          "url": "https://dermnetnz.org/topics/basal-cell-carcinoma",
          "metadataCheckedAt": "2026-09-23"
        }
      ],
      "status": "review required",
      "activeDecisionId": null,
      "history": [],
      "awaitingSections": [
        "prompt",
        "options",
        "best-answer",
        "explanation",
        "safety-notice",
        "references"
      ]
    },
    {
      "id": "psoriasis-distribution",
      "assetType": "quiz",
      "title": "Which distribution best fits the common plaque psoriasis pattern shown in the schematic?",
      "schemaVersion": 1,
      "currentFingerprint": "sha256-v1:c14b5fd12435cf55496cf03dac6dd9fa86ef8096f2293545abdf228f211d607e",
      "sections": [
        "prompt",
        "options",
        "best-answer",
        "explanation",
        "safety-notice",
        "references"
      ],
      "evidenceSources": [
        "https://dermnetnz.org/topics/psoriasis"
      ],
      "evidenceMetadata": [
        {
          "title": "Psoriasis",
          "organization": "DermNet",
          "type": "clinical reference",
          "year": null,
          "version": null,
          "doi": null,
          "url": "https://dermnetnz.org/topics/psoriasis",
          "metadataCheckedAt": "2026-09-20"
        }
      ],
      "status": "review required",
      "activeDecisionId": null,
      "history": [],
      "awaitingSections": [
        "prompt",
        "options",
        "best-answer",
        "explanation",
        "safety-notice",
        "references"
      ]
    },
    {
      "id": "acne-comedones",
      "assetType": "quiz",
      "title": "Which finding most strongly supports acne vulgaris over rosacea in this learning set?",
      "schemaVersion": 1,
      "currentFingerprint": "sha256-v1:2c319607ba93366f090b14f983f558eeb1e8fb4256cf31290b55e6ff9eea8761",
      "sections": [
        "prompt",
        "options",
        "best-answer",
        "explanation",
        "safety-notice",
        "references"
      ],
      "evidenceSources": [
        "https://pubmed.ncbi.nlm.nih.gov/38300170/",
        "https://dermnetnz.org/topics/acne-vulgaris"
      ],
      "evidenceMetadata": [
        {
          "title": "Guidelines of care for the management of acne vulgaris",
          "organization": "American Academy of Dermatology",
          "type": "guideline",
          "year": 2024,
          "version": null,
          "doi": "10.1016/j.jaad.2023.12.017",
          "url": "https://pubmed.ncbi.nlm.nih.gov/38300170/",
          "metadataCheckedAt": "2026-09-20"
        },
        {
          "title": "Acne vulgaris",
          "organization": "DermNet",
          "type": "clinical reference",
          "year": null,
          "version": null,
          "doi": null,
          "url": "https://dermnetnz.org/topics/acne-vulgaris",
          "metadataCheckedAt": "2026-09-20"
        }
      ],
      "status": "review required",
      "activeDecisionId": null,
      "history": [],
      "awaitingSections": [
        "prompt",
        "options",
        "best-answer",
        "explanation",
        "safety-notice",
        "references"
      ]
    },
    {
      "id": "ak-biopsy",
      "assetType": "quiz",
      "title": "What is the appropriate next diagnostic step when an actinic keratosis is persistently thickened, tender or concerning for invasion?",
      "schemaVersion": 1,
      "currentFingerprint": "sha256-v1:99ea95c1e7735771d66d053dd15a67e811b3cd1d0b74fdf5130cfaeda2d08c00",
      "sections": [
        "prompt",
        "options",
        "best-answer",
        "explanation",
        "safety-notice",
        "references"
      ],
      "evidenceSources": [
        "https://onlinelibrary.wiley.com/doi/10.1111/ddg.15231"
      ],
      "evidenceMetadata": [
        {
          "title": "S3 guideline: actinic keratosis and cutaneous squamous cell carcinoma — update 2023, part 1: treatment of actinic keratosis, actinic cheilitis, Bowen disease, occupational disease and structures of care",
          "organization": "German Dermatological Society guideline group / AWMF 032/022OL",
          "type": "guideline",
          "year": 2023,
          "version": "2.0",
          "doi": "10.1111/ddg.15231",
          "url": "https://onlinelibrary.wiley.com/doi/10.1111/ddg.15231",
          "metadataCheckedAt": "2026-09-20"
        }
      ],
      "status": "review required",
      "activeDecisionId": null,
      "history": [],
      "awaitingSections": [
        "prompt",
        "options",
        "best-answer",
        "explanation",
        "safety-notice",
        "references"
      ]
    },
    {
      "id": "atopic-first-line",
      "assetType": "quiz",
      "title": "Which option belongs in the first-line treatment hierarchy for atopic dermatitis?",
      "schemaVersion": 1,
      "currentFingerprint": "sha256-v1:cccedc4756dcca10d65c396241c9e0aacf6a7b068545a80e7a9379b588b87c4c",
      "sections": [
        "prompt",
        "options",
        "best-answer",
        "explanation",
        "safety-notice",
        "references"
      ],
      "evidenceSources": [
        "https://pubmed.ncbi.nlm.nih.gov/36641009/"
      ],
      "evidenceMetadata": [
        {
          "title": "Guidelines of care for the management of atopic dermatitis in adults with topical therapies",
          "organization": "American Academy of Dermatology",
          "type": "guideline",
          "year": 2023,
          "version": null,
          "doi": "10.1016/j.jaad.2022.12.029",
          "url": "https://pubmed.ncbi.nlm.nih.gov/36641009/",
          "metadataCheckedAt": "2026-09-20"
        }
      ],
      "status": "review required",
      "activeDecisionId": null,
      "history": [],
      "awaitingSections": [
        "prompt",
        "options",
        "best-answer",
        "explanation",
        "safety-notice",
        "references"
      ]
    },
    {
      "id": "rosacea-ocular",
      "assetType": "quiz",
      "title": "Which finding should prompt consideration of ophthalmic assessment in rosacea?",
      "schemaVersion": 1,
      "currentFingerprint": "sha256-v1:bf0caec2aad56ec341a0e5b257ca45c49630f89b69c176df8227604abc1ccba5",
      "sections": [
        "prompt",
        "options",
        "best-answer",
        "explanation",
        "safety-notice",
        "references"
      ],
      "evidenceSources": [
        "https://pubmed.ncbi.nlm.nih.gov/35929658/"
      ],
      "evidenceMetadata": [
        {
          "title": "S2k guideline: Rosacea",
          "organization": "German Dermatological Society guideline group",
          "type": "guideline",
          "year": 2022,
          "version": null,
          "doi": "10.1111/ddg.14849",
          "url": "https://pubmed.ncbi.nlm.nih.gov/35929658/",
          "metadataCheckedAt": "2026-09-20"
        }
      ],
      "status": "review required",
      "activeDecisionId": null,
      "history": [],
      "awaitingSections": [
        "prompt",
        "options",
        "best-answer",
        "explanation",
        "safety-notice",
        "references"
      ]
    },
    {
      "id": "tinea-confirmation",
      "assetType": "quiz",
      "title": "When tinea corporis morphology is atypical or treatment fails, which step supports confirmation?",
      "schemaVersion": 1,
      "currentFingerprint": "sha256-v1:d6de482b2d5a79a9ef2a87663522c94468c44ac7ba0805beab4d8455b3fb1b9c",
      "sections": [
        "prompt",
        "options",
        "best-answer",
        "explanation",
        "safety-notice",
        "references"
      ],
      "evidenceSources": [
        "https://www.cdc.gov/ringworm/hcp/clinical-overview/"
      ],
      "evidenceMetadata": [
        {
          "title": "Clinical Overview of Ringworm",
          "organization": "Centers for Disease Control and Prevention",
          "type": "clinical reference",
          "year": 2024,
          "version": null,
          "doi": null,
          "url": "https://www.cdc.gov/ringworm/hcp/clinical-overview/",
          "metadataCheckedAt": "2026-09-20"
        }
      ],
      "status": "review required",
      "activeDecisionId": null,
      "history": [],
      "awaitingSections": [
        "prompt",
        "options",
        "best-answer",
        "explanation",
        "safety-notice",
        "references"
      ]
    },
    {
      "id": "melanoma-abcde-schematic",
      "assetType": "visual",
      "title": "Melanoma ABCDE warning-feature concept",
      "schemaVersion": 1,
      "currentFingerprint": "sha256-v1:d998a1ed1f2f9c5e7379887a8d2e29abd5066f8c3b1f7c28a5b1d8d2967b7845",
      "sections": [
        "image",
        "title",
        "caption",
        "alternative-text",
        "educational-description",
        "legend",
        "safety-notice",
        "provenance"
      ],
      "evidenceSources": [
        "https://github.com/mnasuharas/Docutis/blob/main/assets/media/melanoma-abcde-schematic.svg"
      ],
      "evidenceMetadata": [
        {
          "title": "Docutis original schematic",
          "organization": "Docutis project",
          "type": "illustration",
          "year": null,
          "version": null,
          "doi": null,
          "url": "https://github.com/mnasuharas/Docutis/blob/main/assets/media/melanoma-abcde-schematic.svg",
          "metadataCheckedAt": "2026-09-20"
        }
      ],
      "status": "review required",
      "activeDecisionId": null,
      "history": [],
      "awaitingSections": [
        "image",
        "title",
        "caption",
        "alternative-text",
        "educational-description",
        "legend",
        "safety-notice",
        "provenance"
      ]
    },
    {
      "id": "bcc-clues-schematic",
      "assetType": "visual",
      "title": "Basal cell carcinoma morphology and dermoscopic clues",
      "schemaVersion": 1,
      "currentFingerprint": "sha256-v1:f8732526c38d0364684d2eabf10e8e3fffd762f0725b9c806bf8976423afb3ea",
      "sections": [
        "image",
        "title",
        "caption",
        "alternative-text",
        "educational-description",
        "legend",
        "safety-notice",
        "provenance"
      ],
      "evidenceSources": [
        "https://github.com/mnasuharas/Docutis/blob/main/assets/media/bcc-clues-schematic.svg"
      ],
      "evidenceMetadata": [
        {
          "title": "Docutis original schematic",
          "organization": "Docutis project",
          "type": "illustration",
          "year": null,
          "version": null,
          "doi": null,
          "url": "https://github.com/mnasuharas/Docutis/blob/main/assets/media/bcc-clues-schematic.svg",
          "metadataCheckedAt": "2026-09-20"
        }
      ],
      "status": "review required",
      "activeDecisionId": null,
      "history": [],
      "awaitingSections": [
        "image",
        "title",
        "caption",
        "alternative-text",
        "educational-description",
        "legend",
        "safety-notice",
        "provenance"
      ]
    },
    {
      "id": "psoriasis-distribution-schematic",
      "assetType": "visual",
      "title": "Plaque psoriasis morphology and typical distribution",
      "schemaVersion": 1,
      "currentFingerprint": "sha256-v1:bf730b84197200be4fab44f420cf3f93a6f003b88f2fea372e13f77e361b0768",
      "sections": [
        "image",
        "title",
        "caption",
        "alternative-text",
        "educational-description",
        "legend",
        "safety-notice",
        "provenance"
      ],
      "evidenceSources": [
        "https://github.com/mnasuharas/Docutis/blob/main/assets/media/psoriasis-distribution-schematic.svg"
      ],
      "evidenceMetadata": [
        {
          "title": "Docutis original schematic",
          "organization": "Docutis project",
          "type": "illustration",
          "year": null,
          "version": null,
          "doi": null,
          "url": "https://github.com/mnasuharas/Docutis/blob/main/assets/media/psoriasis-distribution-schematic.svg",
          "metadataCheckedAt": "2026-09-20"
        }
      ],
      "status": "review required",
      "activeDecisionId": null,
      "history": [],
      "awaitingSections": [
        "image",
        "title",
        "caption",
        "alternative-text",
        "educational-description",
        "legend",
        "safety-notice",
        "provenance"
      ]
    },
    {
      "id": "acne-lesions-schematic",
      "assetType": "visual",
      "title": "Acne lesion types and inflammatory depth",
      "schemaVersion": 1,
      "currentFingerprint": "sha256-v1:ecb148b53599f518b7f8a993955af85e6e863ae7a841e7fa1423ea1842a6d69a",
      "sections": [
        "image",
        "title",
        "caption",
        "alternative-text",
        "educational-description",
        "legend",
        "safety-notice",
        "provenance"
      ],
      "evidenceSources": [
        "https://github.com/mnasuharas/Docutis/blob/main/assets/media/acne-lesions-schematic.svg"
      ],
      "evidenceMetadata": [
        {
          "title": "Docutis original schematic",
          "organization": "Docutis project",
          "type": "illustration",
          "year": null,
          "version": null,
          "doi": null,
          "url": "https://github.com/mnasuharas/Docutis/blob/main/assets/media/acne-lesions-schematic.svg",
          "metadataCheckedAt": "2026-09-20"
        }
      ],
      "status": "review required",
      "activeDecisionId": null,
      "history": [],
      "awaitingSections": [
        "image",
        "title",
        "caption",
        "alternative-text",
        "educational-description",
        "legend",
        "safety-notice",
        "provenance"
      ]
    },
    {
      "id": "cutaneous-melanoma-de",
      "assetType": "follow_up",
      "title": "Cutaneous melanoma — Germany",
      "schemaVersion": 1,
      "currentFingerprint": "sha256-v1:7abe145b718e6c0d3c61eaf3277646370a1a58813f1b7e239092f652ad1d9387",
      "sections": [
        "scope",
        "risk-groups",
        "periods",
        "clinical-examination",
        "lymph-node-ultrasound",
        "s100b",
        "cross-sectional-imaging",
        "context",
        "safety-notice",
        "references"
      ],
      "evidenceSources": [
        "https://www.leitlinienprogramm-onkologie.de/fileadmin/user_upload/Downloads/Leitlinien/Melanom/Melanom_Version_3/LL_Melanom_Langversion_3.3.pdf",
        "https://register.awmf.org/assets/guidelines/032-024OLp_S3_Melanom-Diagnostik-Therapie-Nachsorge_2020-08_1.pdf",
        "https://infoportal-hautkrebs.de/hautkrebsarten/malignes-melanom/diagnostik/stadieneinteilung-des-melanoms/in-situ-melanom",
        "https://www.aad.org/public/diseases/skin-cancer/types/common/melanoma/after-diagnosed"
      ],
      "evidenceMetadata": [
        {
          "title": "S3-Leitlinie zur Diagnostik, Therapie und Nachsorge des Melanoms",
          "organization": "Leitlinienprogramm Onkologie (AWMF, Deutsche Krebsgesellschaft, Deutsche Krebshilfe)",
          "type": "DE_S3",
          "year": "2020-07",
          "version": "3.3",
          "doi": null,
          "url": "https://www.leitlinienprogramm-onkologie.de/fileadmin/user_upload/Downloads/Leitlinien/Melanom/Melanom_Version_3/LL_Melanom_Langversion_3.3.pdf",
          "metadataCheckedAt": "2026-09-17"
        },
        {
          "title": "Patient guideline: Melanoma follow-up and early detection",
          "organization": "Leitlinienprogramm Onkologie",
          "type": "official patient guideline",
          "year": "2020-08",
          "version": null,
          "doi": null,
          "url": "https://register.awmf.org/assets/guidelines/032-024OLp_S3_Melanom-Diagnostik-Therapie-Nachsorge_2020-08_1.pdf",
          "metadataCheckedAt": "2026-09-17"
        },
        {
          "title": "In-situ Melanom",
          "organization": "Infoportal Hautkrebs",
          "type": "German expert information",
          "year": "2025-06-23",
          "version": null,
          "doi": null,
          "url": "https://infoportal-hautkrebs.de/hautkrebsarten/malignes-melanom/diagnostik/stadieneinteilung-des-melanoms/in-situ-melanom",
          "metadataCheckedAt": "2026-09-17"
        },
        {
          "title": "I've been diagnosed with melanoma. Now what?",
          "organization": "American Academy of Dermatology",
          "type": "professional society patient guidance",
          "year": "2021-10-27",
          "version": null,
          "doi": null,
          "url": "https://www.aad.org/public/diseases/skin-cancer/types/common/melanoma/after-diagnosed",
          "metadataCheckedAt": "2026-09-17"
        }
      ],
      "status": "review required",
      "activeDecisionId": null,
      "history": [],
      "awaitingSections": [
        "scope",
        "risk-groups",
        "periods",
        "clinical-examination",
        "lymph-node-ultrasound",
        "s100b",
        "cross-sectional-imaging",
        "context",
        "safety-notice",
        "references"
      ]
    },
    {
      "id": "basal-cell-carcinoma-de",
      "assetType": "follow_up",
      "title": "Basal cell carcinoma — Germany",
      "schemaVersion": 1,
      "currentFingerprint": "sha256-v1:7100e89eed023219b5610e3973cf5f8d441daf8bad70a63deb329c83d275a7c1",
      "sections": [
        "scope",
        "risk-groups",
        "periods",
        "clinical-examination",
        "lymph-node-ultrasound",
        "s100b",
        "cross-sectional-imaging",
        "context",
        "safety-notice",
        "references"
      ],
      "evidenceSources": [
        "https://register.awmf.org/assets/guidelines/032-021l_S2k_Basalzellkarzinom-der-Haut_2024-07.pdf"
      ],
      "evidenceMetadata": [
        {
          "title": "S2k-Leitlinie Basalzellkarzinom der Haut (Aktualisierung 2023)",
          "organization": "AWMF / Deutsche Krebsgesellschaft / Deutsche Dermatologische Gesellschaft / ADO",
          "type": "DE_S2K",
          "year": "2024-01",
          "version": "9.0",
          "doi": null,
          "url": "https://register.awmf.org/assets/guidelines/032-021l_S2k_Basalzellkarzinom-der-Haut_2024-07.pdf",
          "metadataCheckedAt": "2026-09-16"
        }
      ],
      "status": "review required",
      "activeDecisionId": null,
      "history": [],
      "awaitingSections": [
        "scope",
        "risk-groups",
        "periods",
        "clinical-examination",
        "lymph-node-ultrasound",
        "s100b",
        "cross-sectional-imaging",
        "context",
        "safety-notice",
        "references"
      ]
    },
    {
      "id": "cutaneous-squamous-cell-carcinoma-de",
      "assetType": "follow_up",
      "title": "Cutaneous squamous cell carcinoma — Germany",
      "schemaVersion": 1,
      "currentFingerprint": "sha256-v1:d53155d28c31fea31c5b0b4e6b9ec57514002a2fa158a00fd8ecbdbdd5a984c7",
      "sections": [
        "scope",
        "risk-groups",
        "periods",
        "clinical-examination",
        "lymph-node-ultrasound",
        "s100b",
        "cross-sectional-imaging",
        "context",
        "safety-notice",
        "references"
      ],
      "evidenceSources": [
        "https://www.leitlinienprogramm-onkologie.de/fileadmin/user_upload/Downloads/Leitlinien/Aktinische_Keratosen_und_PEK/Version_2/LL_Aktinische_Keratose_und_PEK_Langversion_2.0.pdf"
      ],
      "evidenceMetadata": [
        {
          "title": "S3-Leitlinie Aktinische Keratose und Plattenepithelkarzinom der Haut",
          "organization": "Leitlinienprogramm Onkologie (AWMF, Deutsche Krebsgesellschaft, Deutsche Krebshilfe)",
          "type": "DE_S3",
          "year": "2022-12",
          "version": "2.0",
          "doi": null,
          "url": "https://www.leitlinienprogramm-onkologie.de/fileadmin/user_upload/Downloads/Leitlinien/Aktinische_Keratosen_und_PEK/Version_2/LL_Aktinische_Keratose_und_PEK_Langversion_2.0.pdf",
          "metadataCheckedAt": "2026-09-16"
        }
      ],
      "status": "review required",
      "activeDecisionId": null,
      "history": [],
      "awaitingSections": [
        "scope",
        "risk-groups",
        "periods",
        "clinical-examination",
        "lymph-node-ultrasound",
        "s100b",
        "cross-sectional-imaging",
        "context",
        "safety-notice",
        "references"
      ]
    }
  ]
});
